support retention for cloudwatch_logs output
fluent/fluent-bit pull request #2739
Opened 2020-10-31 12:00 UTC by shogo82148

support retention for `cloudwatch_logs` output plugin.
introduce a new property `log_retention_days`.

Addresses #2691

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [ ] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2020-11-12 22:53 UTC, PettitWesley commented
Thank you for working on adding this to the new core cloudwatch logs plugin!

2020-11-12 22:53 UTC, PettitWesley commented
Per the contributing guide: https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md

You commit message should be something like: `out_cloudwatch_logs: add log_retention_days option"

2020-11-12 23:56 UTC, shogo82148 commented
Thanks. I updated the commit message.

2020-11-16 06:11 UTC, PettitWesley requested changes
Thanks again for contributing this. I added a few more comments (sorry, I didn't have time to do full review before). I also tested it- once these are fixed we can merge it.

If you have time, please also submit a PR to the docs repo and @ mention me on it: https://github.com/fluent/fluent-bit-docs

If not, let me know, and I will submit the PR for docs.

2020-11-16 06:11 UTC, PettitWesley commented on plugins/out_cloudwatch_logs/cloudwatch_api.c
> +    return 0;
Should be `return -1` since the call failed

2020-11-16 06:11 UTC, PettitWesley commented on plugins/out_cloudwatch_logs/cloudwatch_api.c
> +            return set_log_group_retention(ctx);
nit: Eduardo has told me that in C it is not good style to return a function call. So instead:

```
ret = set_log_group_retention(ctx);
return ret;
```

2020-11-16 06:11 UTC, PettitWesley commented on plugins/out_cloudwatch_logs/cloudwatch_logs.c
> +     "retention policy is set to this many days."
Nit: For some reason that I do not understand the CloudWatch Logs API only supports a few values for retention:

```
[2020/11/16 05:56:10] [error] [output:cloudwatch_logs:cloudwatch_logs.0] PutRetentionPolicy API responded with error='InvalidParameterException', message='Invalid retention value. Valid values are: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]'
```

You could put the valid values list in the help text here

2020-11-16 06:11 UTC, PettitWesley commented on tests/runtime/out_cloudwatch.c
> +    {"error_put_retention_policy", flb_test_cloudwatch_error_put_retention_policy },
Thank you for adding tests!

2020-11-16 12:16 UTC, shogo82148 commented
Thank you for your review!
I fixed them, and created a new pull request on fluent-bit-docs https://github.com/fluent/fluent-bit-docs/pull/419

2020-11-16 18:33 UTC, PettitWesley commented on plugins/out_cloudwatch_logs/cloudwatch_api.c
> +            int ret = set_log_group_retention(ctx);
always declare variables at the top of the function, per the style guide: https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#variable-definitions

2020-11-16 18:33 UTC, PettitWesley commented
One new comment... then I think this is ready

2020-11-16 21:15 UTC, PettitWesley commented
Hey, actually, thinking about this some more, can you modify the code so that the retention policy is set even if the log group already exists.

Right now you only set the retention policy if the CreateLogGroup API responds with 200 success. You can also set the retention policy if it responds that the group already exists (which is a few lines down in the create group function)


This has been requested: https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/issues/121

2020-11-23 07:54 UTC, shogo82148 commented
Sorry for my late response.
I fixed variable declaration https://github.com/fluent/fluent-bit/pull/2739#discussion_r524486276 and set the retention policy of the group already exists.

2020-11-24 06:11 UTC, PettitWesley approved these changes
Thanks!

2020-11-24 06:12 UTC, merged

2021-03-12 09:07 UTC, shogo82148 commented
#2691 is not stale, but done.
Can someone close it? I have no permission to do it.