Fix cmake configuration for building on Windows
fluent/fluent-bit pull request #2945
Opened 2021-01-14 16:27 UTC by jeremyje

Fluent-bit in it's current state does not build on Windows. This can be verified by simply running `docker build -f Dockerfile.windows.devel`.

There were a few issues:

* `flb_io_net_connect` was marked as inline, so it couldn't be used outside the `flb_io.c` file in Visual Studio.
* `CMakeLists.txt` had some compiler flags that were Linux only passed to Windows as well.
* The `if(NOT ${CMAKE_SYSTEM_NAME} MATCHES "Windows")` was not effective. I removed the `NOT` and flipped the statement.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [X] Example configuration file for the change
- [X] Debug log output from testing the change

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [ ] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2021-01-14 19:46 UTC, jeremyje commented
Running the CI locally on my machine.

One caveat here is this is running on Visual Studio 2019 but it should run on the Visual Studio 2016 that is backed by AppVeyor.

```
.\do-ut.ps1


    Directory: C:\projects\fixwin\fluent-bit\ci


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         1/14/2021  11:35 AM                build
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is MSVC 19.28.29336.0
-- The CXX compiler identification is MSVC 19.28.29336.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx86/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx86/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: C:/WinBuilds/bin/pkg-config.exe (found version "0.25")
-- Could NOT find Journald (missing: JOURNALD_LIBRARY JOURNALD_INCLUDE_DIR)
-- Found Monkey: C:/projects/fixwin/fluent-bit/lib/monkey/include
-- Found FLEX: C:/Apps/flex.exe (found version "2.6.4")
-- Found BISON: C:/Apps/bison.exe (found version "3.7.4")
-- Enabling FLB_REGEX since FLB_PARSER requires
CMake Deprecation Warning at lib/msgpack-c/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Searching 16 bit integer - Using unsigned short
-- Check if the system is big endian - little endian
CMake Deprecation Warning at lib/tutf8e/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- xxHash build type: Debug
-- Performing Test CFLAG_Wall
-- Performing Test CFLAG_Wall - Success
-- Performing Test CFLAG_Wextra
-- Performing Test CFLAG_Wextra - Failed
-- Performing Test CFLAG_Wcast_qual
-- Performing Test CFLAG_Wcast_qual - Failed
-- Performing Test CFLAG_Wcast_align
-- Performing Test CFLAG_Wcast_align - Failed
-- Performing Test CFLAG_Wshadow
-- Performing Test CFLAG_Wshadow - Failed
-- Performing Test CFLAG_Wstrict_aliasing_1
-- Performing Test CFLAG_Wstrict_aliasing_1 - Failed
-- Performing Test CFLAG_Wswitch_enum
-- Performing Test CFLAG_Wswitch_enum - Failed
-- Performing Test CFLAG_Wdeclaration_after_statement
-- Performing Test CFLAG_Wdeclaration_after_statement - Failed
-- Performing Test CFLAG_Wstrict_prototypes
-- Performing Test CFLAG_Wstrict_prototypes - Failed
-- Performing Test CFLAG_Wundef
-- Performing Test CFLAG_Wundef - Failed
CMake Deprecation Warning at lib/chunkio/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Performing Test CIO_HAVE_FALLOCATE
-- Performing Test CIO_HAVE_FALLOCATE - Failed
CMake Warning (dev) at lib/monkey/mk_core/deps/CMakeLists.txt:2 (set):
  implicitly converting '' to 'STRING' type.
Call Stack (most recent call first):
  lib/monkey/mk_core/deps/CMakeLists.txt:5 (FORCE_OPTION)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at lib/monkey/mk_core/deps/CMakeLists.txt:2 (set):
  implicitly converting '' to 'STRING' type.
Call Stack (most recent call first):
  lib/monkey/mk_core/deps/CMakeLists.txt:6 (FORCE_OPTION)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at lib/monkey/mk_core/deps/CMakeLists.txt:2 (set):
  implicitly converting '' to 'STRING' type.
Call Stack (most recent call first):
  lib/monkey/mk_core/deps/CMakeLists.txt:7 (FORCE_OPTION)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at lib/monkey/mk_core/deps/CMakeLists.txt:2 (set):
  implicitly converting '' to 'STRING' type.
Call Stack (most recent call first):
  lib/monkey/mk_core/deps/CMakeLists.txt:8 (FORCE_OPTION)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at lib/monkey/mk_core/deps/CMakeLists.txt:2 (set):
  implicitly converting '' to 'STRING' type.
Call Stack (most recent call first):
  lib/monkey/mk_core/deps/CMakeLists.txt:9 (FORCE_OPTION)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at lib/monkey/mk_core/deps/CMakeLists.txt:2 (set):
  implicitly converting '' to 'STRING' type.
Call Stack (most recent call first):
  lib/monkey/mk_core/deps/CMakeLists.txt:10 (FORCE_OPTION)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at lib/monkey/mk_core/deps/CMakeLists.txt:2 (set):
  implicitly converting '' to 'STRING' type.
Call Stack (most recent call first):
  lib/monkey/mk_core/deps/CMakeLists.txt:11 (FORCE_OPTION)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Git: C:/Program Files/Git/cmd/git.exe
fatal: No annotated tags can describe 'b368e9b6d0008a82b310fbba33ce5b04d8dc1c6c'.
However, there were unannotated tags: try --tags.
-- Looking for __GNU_LIBRARY__
-- Looking for __GNU_LIBRARY__ - not found
-- Looking for sys/types.h
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.19/Modules/CheckIncludeFile.cmake:80 (message):
  Policy CMP0075 is not set: Include file check macros honor
  CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  CMAKE_REQUIRED_LIBRARIES is set to:

    ws2_32.lib

  For compatibility with CMake 3.11 and below this check is ignoring it.
Call Stack (most recent call first):
  lib/monkey/mk_core/deps/libevent/CMakeLists.txt:232 (CHECK_INCLUDE_FILE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for sys/types.h - found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - not found
-- Looking for netinet/in.h
-- Looking for netinet/in.h - not found
-- Looking for netinet/in6.h
-- Looking for netinet/in6.h - not found
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Looking for netdb.h
-- Looking for netdb.h - not found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - not found
-- Looking for arpa/inet.h
-- Looking for arpa/inet.h - not found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for poll.h
-- Looking for poll.h - not found
-- Looking for port.h
-- Looking for port.h - not found
-- Looking for signal.h
-- Looking for signal.h - found
-- Looking for stdarg.h
-- Looking for stdarg.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Looking fo [...]

2021-01-20 10:28 UTC, fujimotos requested changes

2021-01-20 10:28 UTC, fujimotos commented on lib/mpack-amalgamation-1.0/CMakeLists.txt
> +else()
You need to upstream this changes to https://github.com/ludocode/mpack.
We generally avoid hand-patching upstream libraries.

2021-01-20 10:28 UTC, fujimotos commented on lib/monkey/CMakeLists.txt
> +if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
Ditto. Separate out this changeset and submit it to monkey/monkey.

2021-01-20 10:28 UTC, fujimotos commented on Dockerfile.windows.devel
> +RUN cmake -G "'Visual Studio 16 2019'" -DCMAKE_BUILD_TYPE=Release -DFLB_HTTP_SERVER=No ../;
Can you add this flag to `cmake/windows.cmake`? This will enable
us to simply do like this:

```
$ cmake ..
$ cmake --build .
```

2021-01-20 10:28 UTC, fujimotos commented on README.md
> +cmake -D FLB_HTTP_SERVER=No -D FLB_RELEASE=Yes -D FLB_DEBUG=No ..
FWIW you can speed up the build speed by 2x by setting `-G NMake Makefiles`.
CMake is surprisingly slow at Visual Studio project generation.

For details, please refer to the commit message of ad0d67aa61d758b9f3f3061a36af4cbea1fa4fec.

2021-01-20 10:28 UTC, fujimotos commented on lib/mbedtls-2.24.0/CMakeLists.txt
> +  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99")
We need to submit this changeset to ARMmbed/mbedtls

2022-10-04 04:57 UTC, closed without merging