stream_processor: add necessary check to prevent potential SIGSEGV
fluent/fluent-bit pull request #3053
Opened 2021-02-10 18:10 UTC by yongtang

While checking the stream processor code, noticed there is one
place where flb_calloc does not follow an appropriate null pointer
check.

This PR adds necessary check to prevent potential SIGSEGV.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [N/A] Debug log output from testing the change

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [N/A] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2021-02-10 20:07 UTC, edsiper requested changes

2021-02-10 20:07 UTC, edsiper commented on src/stream_processor/flb_sp.c
> +                flb_sp_aggr_node_destroy(cmd, aggr_node);
thanks. can you add also flb_errno() ?

2021-02-10 20:18 UTC, yongtang commented
Thanks @edsiper for the review. The PR has been updated (I also added the `flb_errno()` in several other places that was missing). Please take a look.

2021-02-10 20:26 UTC, merged

2021-02-10 20:26 UTC, edsiper commented
thanks

2021-02-11 10:34 UTC, l2dy commented
I think this PR broke the AppVeyor CI.

2021-02-11 13:33 UTC, yongtang commented
@edsiper @l2dy Apology for the CI break. I have created a PR #3064 to revert the commit for now. Please take a look.