in_http: add support for json arrays (for lambda extension logs support)
fluent/fluent-bit pull request #3297
Opened 2021-03-29 06:47 UTC by PettitWesley

Signed-off-by: Wesley Pettit <wppttt@amazon.com>

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [ ] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2021-04-02 02:37 UTC, edsiper requested changes

2021-04-02 02:37 UTC, edsiper commented on plugins/in_http/http_prot.c
> +            flb_info("map!");
:information_source:  ?

2021-04-02 02:37 UTC, edsiper commented on plugins/in_http/http_prot.c
> +        } else if (result.data.type == MSGPACK_OBJECT_ARRAY) {
use a new line..

2021-04-02 02:37 UTC, edsiper commented on plugins/in_http/http_prot.c
> +            for (int i = 0; i < obj->via.array.size; i++)
please do not declare a variable on the ```for``` statement, that breaks with old compilers (e.g: centos 7)

2021-04-02 18:48 UTC, PettitWesley commented on plugins/in_http/http_prot.c
> +            flb_info("map!");
oops

2021-04-03 15:39 UTC, edsiper commented
once the changes are in place we can merge it.

2021-04-07 01:18 UTC, PettitWesley commented
@edsiper Addressed comments. I also added a new commit which adds an option tag_key which allows the user to select the tag based on a key in the record. This is also needed for Lambda support.

2021-04-27 18:17 UTC, PettitWesley commented
@edsiper Can we merge this?

2021-04-28 20:39 UTC, edsiper approved these changes

2021-04-28 20:40 UTC, merged