workflows: do not stale Windows-related issues
fluent/fluent-bit pull request #3347
Opened 2021-04-09 08:42 UTC by fujimotos

This stale bot is useful. But it sometimes closes long-term stuffs
which do not expect an immediate update, but still are not dead.

This teaches stale bots to exempt Windows issues (which I manage)
from automatic cleanups.

Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>

2021-04-09 21:06 UTC, niedbalski commented
Makes sense , however, @fujimotos I prefer to have a long-term label or so that we can set it at any PR(s) that needs long term. Can you set it to 'long-term-work' or similar instead ?

2021-04-13 02:32 UTC, niedbalski commented on .github/workflows/pr-stale.yaml
> +          exempt-issue-labels: 'Windows'
can you switch it to 'long-term'?

2021-04-13 02:33 UTC, niedbalski requested changes
LGTM, please review the observation.

2021-04-13 16:25 UTC, edsiper commented
@niedbalski should we wait for the requested change ? (got confused with the LGTM)

2021-04-14 15:37 UTC, niedbalski commented
#3360 fixes it.

2021-04-14 15:37 UTC, closed without merging