http_client: use slist function for NO_PROXY parsing
fluent/fluent-bit pull request #3482
Opened 2021-05-14 13:38 UTC by erain

This is a follow up PR for https://github.com/fluent/fluent-bit/pull/3272
- make use the functions from `slist`
- enhance the unit tests for `slist`

2021-05-14 13:41 UTC, JeffLuoo commented on src/flb_config.c
> +
extra newline?

2021-05-14 13:43 UTC, erain commented
@edsiper @qingling128 I just found that I missed pushing a commit (different dev machine etc.) for the original PR. 

Sorry for the mess up. Could you help review this PR and cherry-pick it for 1.7.5 release if possible? 

Thanks!!

2021-05-14 13:53 UTC, erain commented on src/flb_config.c
> +
Done

2021-05-14 14:13 UTC, erain commented
I've also added the documentation PR in https://github.com/fluent/fluent-bit-docs/pull/532

2021-05-14 14:19 UTC, erain commented
/remove docs-required

2021-05-14 17:56 UTC, ekund commented
I have tested this as well, and it addresses the issues I've been seeing, in https://github.com/fluent/fluent-bit/issues/3483.

2021-05-14 18:07 UTC, qingling128 commented
@erain Unfortunately 1.7.5 is out already. We are discussing offline the potential to do a 1.7.6 release next week for this.

2021-05-14 18:25 UTC, erain commented
Thanks @qingling128 and releasing it in 1.7.6 sounds great.

2021-05-14 19:04 UTC, qingling128 submitted a review, later dismissed
LGTM

2021-05-17 21:03 UTC, erain commented
@edsiper could you help review this PR as well as the doc PR in https://github.com/fluent/fluent-bit-docs/pull/532 ?

2021-05-18 00:59 UTC, edsiper requested changes

2021-05-18 00:59 UTC, edsiper commented on src/flb_config.c
> +/* emptyval checks whether a string has a non-null value "". */
why the string function was moved to flb_config.c ?

2021-05-18 00:59 UTC, edsiper commented on src/flb_upstream.c
> +    if (&no_proxy_list) {
this check is invalid, ```no_proxy_list``` is a variable from the stack, if you want to check if it's empty can use mk_list_size(&no_proxy_list)  == 0 (to check if it has zero nodes linked)

2021-05-18 00:59 UTC, edsiper commented on src/flb_upstream.c
> +        flb_slist_destroy(&no_proxy_list);
it's safe to destroy an initialized empty list... so the above conditional is not required

2021-05-19 16:31 UTC, qingling128 commented
Thanks @erain ! 

@edsiper - Could you take another look?

2021-05-19 17:05 UTC, edsiper approved these changes

2021-05-19 17:05 UTC, merged