network: modify flb_net_getaddrinfo error code
fluent/fluent-bit pull request #3670
Opened 2021-06-19 08:23 UTC by nokute78

The error code of `flb_net_getaddrinfo` is not compatible with getaddrinfo(3).
So,   `gai_strerror` reports useless error log. Note:#3661
This patch is to fix it.

The error code is set at `flb_net_getaddrinfo_callback` and it is came from `ares_getaddrinfo`.
https://c-ares.haxx.se/ares_getaddrinfo.html

undocumented error ARES_ESERVICE is returned when strtoul(service, ..) failed.
https://github.com/fluent/fluent-bit/blob/a11cb4abc6b9dac16a2065b0182a962b215ba353/lib/c-ares-809d5e84/src/lib/ares_getaddrinfo.c#L617

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [N/A] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [N/A] Documentation required for this feature

## Valgrind output
```
$ valgrind --leak-check=full bin/fluent-bit  -i http -p host=localhost -o stdout
==51893== Memcheck, a memory error detector
==51893== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==51893== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==51893== Command: bin/fluent-bit -i http -p host=localhost -o stdout
==51893== 
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/06/19 17:20:29] [ info] [engine] started (pid=51893)
[2021/06/19 17:20:29] [ info] [storage] version=1.1.1, initializing...
[2021/06/19 17:20:29] [ info] [storage] in-memory
[2021/06/19 17:20:29] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/06/19 17:20:29] [ info] [input:http:http.0] listening on 0.0.0.0:9880
[2021/06/19 17:20:29] [ info] [sp] stream processor started
^C[2021/06/19 17:20:32] [engine] caught signal (SIGINT)
[2021/06/19 17:20:32] [ warn] [engine] service will stop in 5 seconds
[2021/06/19 17:20:37] [ info] [engine] service stopped
==51893== 
==51893== HEAP SUMMARY:
==51893==     in use at exit: 0 bytes in 0 blocks
==51893==   total heap usage: 238 allocs, 238 frees, 261,269 bytes allocated
==51893== 
==51893== All heap blocks were freed -- no leaks are possible
==51893== 
==51893== For lists of detected and suppressed errors, rerun with: -s
==51893== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2021-06-19 10:34 UTC, nokute78 commented
Note: Windows doesn't support `EAI_SYSTEM`.
https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfo#return-value

2021-06-24 03:18 UTC, edsiper requested changes

2021-06-24 03:18 UTC, edsiper commented on src/flb_network.c
> +            // Currently, translation fails when malloc error occured.
pls use proper inline comment style:

https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#single-line-comment

2021-06-24 03:20 UTC, edsiper commented
cc: @leonardo-albertovich

2021-06-25 22:14 UTC, nokute78 commented on src/flb_network.c
> +            // Currently, translation fails when malloc error occured.
Oops, I updated.

2021-06-30 20:27 UTC, leonardo-albertovich commented
I think those changes are correct and the PR is ready to be merged.

2021-07-01 02:14 UTC, merged

2021-07-01 02:14 UTC, edsiper commented
thanks