network : assorted improvements
fluent/fluent-bit pull request #3822
Opened 2021-07-21 20:38 UTC by leonardo-albertovich

network : The primary async  DNS mode can now be selected globally and overriden on a per plugin basis

network : Refactored the async DNS event loop interaction to prevent a corner case where a use after free would happen if there was more than one event for a DNS lookup socket where one of the events satisfied the lookup request and triggered context cleanup.

network : Re-added UDP support with a new artificial timeout mechanism.

2021-07-21 20:39 UTC, leonardo-albertovich commented
Please do not waive this untill [3821](https://github.com/fluent/fluent-bit/pull/3821) is merged into master and I merge master into this branch, that way the tests will pass.

2021-07-21 21:02 UTC, edsiper requested changes

2021-07-21 21:02 UTC, edsiper commented on src/flb_engine.c
> +                if (0 == lookup_context->finished) {
for boolean kind check let's use:

 ```c
 if (!lookup_context->finished) {
 }
 ```

2021-07-21 21:02 UTC, edsiper commented on src/flb_network.c
> +    if (context->finished == 1) {
```c
if (context->finished) {
 ....
}
```

2021-07-21 21:03 UTC, leonardo-albertovich commented on src/flb_engine.c
> +                if (0 == lookup_context->finished) {
Sure

2021-07-26 20:59 UTC, merged

2021-08-01 04:15 UTC, nokute78 commented
This PR may causes memory leak. #3897 
Previous commit https://github.com/fluent/fluent-bit/commit/ef5fb2c677b0321cd9e243cd7a2786cd4688c249 works without leaks.

Please check using valgrind...