Add 'out_ws_nats' plugin to emit messages through NATS WebSocket
fluent/fluent-bit pull request #3859
Opened 2021-07-26 18:34 UTC by wallyqs

This adds an output plugin that enables output of NATS events by connecting to its websocket port.  This is based on the websocket module so can potentially reuse some of the machinery present to create TLS connections which is not possible with the current nats plugin.

----

**Testing**

Before we can approve your change; please submit the following in a comment:

- [X] Example configuration file for the change

```sh
[INPUT]
    Name        tcp
    Listen      0.0.0.0
    Port        5170
    Format      json
[OUTPUT]
    Name           ws_nats
    Match          *
    Host           127.0.0.1
    Port           443
    URI            /
    Format         json
    tls            On
    tls.ca_file    /tmp/ca.pem
```

- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [ ] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

Signed-off-by: Waldemar Quevedo <wally@synadia.com>

2021-10-05 07:43 UTC, nokute78 requested changes
I reviewed and commented.

I also request below points.

- Could you attach valgrind output ?
- Could you add test code ?
- Could you `flb_plg_` APIs instead of `flb_error`/`flb_info`/`flb_debug`. They are defined at `flb_output_plugin.h`

2021-10-05 07:43 UTC, nokute78 commented on plugins/out_ws_nats/ws_nats.c
> +        connect_proto_len = snprintf(connect_proto, sizeof(NATS_CONNECT), NATS_CONNECT);
I think these values should be allocated only once since NATS_CONNECT is a static string.

Is `connect_proto` released after using?

2021-10-05 07:43 UTC, nokute78 commented on plugins/out_ws_nats/ws_nats.c
> +    request = flb_malloc(json_len + tag_len + 32);
Is `request` released after using?

2021-11-23 02:08 UTC, edsiper commented
@wallyqs 

sorry for the delay.

Some requirements to get this merged:

- address code changes requested / comments
- rename the plugin from out_ws_nats to out_nats_websockets
  - interface prefix for code can start with nats_ws
  - adjust flush callback prototype (it recently changed a bit)

2022-02-24 03:49 UTC, wallyqs commented
Thanks everyone for the review, might be easier to reopen at some point using a rebased version of the branch so closing for now.

2022-02-24 03:49 UTC, closed without merging