Add NGINX Plus metrics
fluent/fluent-bit pull request #4379
Opened 2021-11-30 14:49 UTC by pwhelan

This expands the current stub_status to support grabbing stats from the NGINX Plus REST stats API.

----

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change
- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**
- [ ] Documentation required for this feature

TODO:

  [ ] detect API version to avoid scraping data that is not available.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2021-11-30 17:12 UTC, edsiper requested changes
commented initial part of the code, most of these applies to other parts of the PR

2021-11-30 17:12 UTC, edsiper commented on plugins/in_nginx_exporter_metrics/nginx.c
> +            msgpack_sbuffer_init(&mp_sbuf);
this code is unused, the buffer will leak memory

2021-11-30 17:12 UTC, edsiper commented on plugins/in_nginx_exporter_metrics/nginx.c
> +            msgpack_sbuffer_init(&mp_sbuf);
this code is unused, the buffer will leak memory

2021-11-30 17:12 UTC, edsiper commented on plugins/in_nginx_exporter_metrics/nginx.c
> +                if (strncmp(result.data.via.map.ptr[i].key.via.str.ptr, "handshakes", result.data.via.map.ptr[i].key.via.str.size) == 0) {
lines too long, use approach suggested above

2021-12-02 13:04 UTC, pwhelan commented
```
valgrind ./bin/fluent-bit -vvv -i nginx_metrics -p host=172.17.0.2 -p port=80 -p nginx_plus=on -p status_url=/api/ -o stdout -m '*' -o exit -m '*' -f 1
==171874== Memcheck, a memory error detector
==171874== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==171874== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==171874== Command: ./bin/fluent-bit -vvv -i nginx_metrics -p host=172.17.0.2 -p port=80 -p nginx_plus=on -p status_url=/api/ -o stdout -m * -o exit -m * -f 1
==171874== 
Fluent Bit v1.9.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/12/02 10:00:59] [ info] Configuration:
[2021/12/02 10:00:59] [ info]  flush time     | 1.000000 seconds
[2021/12/02 10:00:59] [ info]  grace          | 5 seconds
[2021/12/02 10:00:59] [ info]  daemon         | 0
[2021/12/02 10:00:59] [ info] ___________
[2021/12/02 10:00:59] [ info]  inputs:
[2021/12/02 10:00:59] [ info]      nginx_metrics
[2021/12/02 10:00:59] [ info] ___________
[2021/12/02 10:00:59] [ info]  filters:
[2021/12/02 10:00:59] [ info] ___________
[2021/12/02 10:00:59] [ info]  outputs:
[2021/12/02 10:00:59] [ info]      stdout.0
[2021/12/02 10:00:59] [ info]      exit.1
[2021/12/02 10:00:59] [ info] ___________
[2021/12/02 10:00:59] [ info]  collectors:
[2021/12/02 10:00:59] [ info] [engine] started (pid=171874)
[2021/12/02 10:00:59] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2021/12/02 10:00:59] [debug] [storage] [cio stream] new stream registered: nginx_metrics.0
[2021/12/02 10:00:59] [ info] [storage] version=1.1.5, initializing...
[2021/12/02 10:00:59] [ info] [storage] in-memory
[2021/12/02 10:00:59] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/12/02 10:00:59] [ info] [cmetrics] version=0.2.2
[2021/12/02 10:00:59] [ info] [input:nginx_metrics:nginx_metrics.0] nginx-plus mode on
[2021/12/02 10:00:59] [debug] [stdout:stdout.0] created event channels: read=19 write=20
[2021/12/02 10:00:59] [debug] [exit:exit.1] created event channels: read=21 write=22
[2021/12/02 10:00:59] [debug] [router] match rule nginx_metrics.0:stdout.0
[2021/12/02 10:00:59] [debug] [router] data generated by nginx_metrics.0 input are metrics, but matching destination plugin exit.1 don't handle metrics.Skipping destination.
[2021/12/02 10:00:59] [ info] [sp] stream processor started
[2021/12/02 10:00:59] [debug] [http_client] not using http_proxy for header
[2021/12/02 10:00:59] [debug] [upstream] KA connection #27 to 172.17.0.2:80 is now available
[2021/12/02 10:00:59] [debug] [upstream] KA connection #27 to 172.17.0.2:80 has been assigned (recycled)
[2021/12/02 10:00:59] [debug] [http_client] not using http_proxy for header
[2021/12/02 10:00:59] [debug] [upstream] KA connection #27 to 172.17.0.2:80 is now available
[2021/12/02 10:00:59] [debug] [upstream] KA connection #27 to 172.17.0.2:80 has been assigned (recycled)
[2021/12/02 10:00:59] [debug] [http_client] not using http_proxy for header
[2021/12/02 10:00:59] [debug] [upstream] KA connection #27 to 172.17.0.2:80 is now available
[2021/12/02 10:00:59] [debug] [upstream] KA connection #27 to 172.17.0.2:80 has been assigned (recycled)
[2021/12/02 10:00:59] [debug] [http_client] not using http_proxy for header
[2021/12/02 10:00:59] [debug] [upstream] KA connection #27 to 172.17.0.2:80 is now available
[2021/12/02 10:00:59] [debug] [upstream] KA connection #27 to 172.17.0.2:80 has been assigned (recycled)
[2021/12/02 10:00:59] [debug] [http_client] not using http_proxy for header
[2021/12/02 10:00:59] [debug] [upstream] KA connection #27 to 172.17.0.2:80 is now available
[2021/12/02 10:00:59] [debug] [upstream] KA connection #27 to 172.17.0.2:80 has been assigned (recycled)
[2021/12/02 10:00:59] [debug] [http_client] not using http_proxy for header
[2021/12/02 10:00:59] [debug] [upstream] KA connection #27 to 172.17.0.2:80 is now available
[2021/12/02 10:00:59] [debug] [upstream] KA connection #27 to 172.17.0.2:80 has been assigned (recycled)
[2021/12/02 10:00:59] [debug] [http_client] not using http_proxy for header
[2021/12/02 10:00:59] [debug] [upstream] KA connection #27 to 172.17.0.2:80 is now available
[2021/12/02 10:00:59] [debug] [upstream] KA connection #27 to 172.17.0.2:80 has been assigned (recycled)
[2021/12/02 10:00:59] [debug] [http_client] not using http_proxy for header
[2021/12/02 10:00:59] [debug] [upstream] KA connection #27 to 172.17.0.2:80 is now available
[2021/12/02 10:00:59] [debug] [upstream] KA connection #27 to 172.17.0.2:80 has been assigned (recycled)
[2021/12/02 10:00:59] [debug] [http_client] not using http_proxy for header
[2021/12/02 10:00:59] [debug] [upstream] KA connection #27 to 172.17.0.2:80 is now available
[2021/12/02 10:00:59] [debug] [input] destroy input_thread id=0
^C[2021/12/02 10:01:00] [engine] caught signal (SIGINT)
2021-12-02T13:00:59.694214367Z nginxplus_connections_accepted = 17
2021-12-02T13:00:59.694214367Z nginxplus_connections_dropped = 0
2021-12-02T13:00:59.694214367Z nginxplus_connections_active = 1
2021-12-02T13:00:59.694214367Z nginxplus_connections_idle = 0
2021-12-02T13:00:59.694214367Z nginxplus_ssl_handshakes = 0
2021-12-02T13:00:59.694214367Z nginxplus_ssl_handshakes_failed = 0
2021-12-02T13:00:59.694214367Z nginxplus_ssl_session_reuses = 0
2021-12-02T13:00:59.694214367Z nginxplus_http_requests_total = 297
2021-12-02T13:00:59.694214367Z nginxplus_http_requests_current = 1
2021-12-02T13:00:59.694214367Z nginxplus_server_zone_discarded{server_zone="thezone"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_server_zone_processing{server_zone="thezone"} = 1
2021-12-02T13:00:59.694214367Z nginxplus_server_zone_received{server_zone="thezone"} = 22840
2021-12-02T13:00:59.694214367Z nginxplus_server_zone_requests{server_zone="thezone"} = 298
2021-12-02T13:00:59.694214367Z nginxplus_server_zone_responses{server_zone="thezone",code="1xx"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_server_zone_responses{server_zone="thezone",code="2xx"} = 297
2021-12-02T13:00:59.694214367Z nginxplus_server_zone_responses{server_zone="thezone",code="3xx"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_server_zone_responses{server_zone="thezone",code="4xx"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_server_zone_responses{server_zone="thezone",code="5xx"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_server_zone_sent{server_zone="thezone"} = 124056
2021-12-02T13:00:59.694214367Z nginxplus_server_zone_discarded{location_zone="dangerzone"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_location_zone_received{location_zone="dangerzone"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_location_zone_requests{location_zone="dangerzone"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_location_zone_responses{location_zone="dangerzone",code="1xx"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_location_zone_responses{location_zone="dangerzone",code="2xx"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_location_zone_responses{location_zone="dangerzone",code="3xx"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_location_zone_responses{location_zone="dangerzone",code="4xx"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_location_zone_responses{location_zone="dangerzone",code="5xx"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_location_zone_sent{location_zone="dangerzone"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_upstream_server_fails{upstream="backend_1",server="192.168.1.146:80"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_upstream_server_fails{upstream="backend_1",server="192.168.1.11:80"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_upstream_server_received{upstream="backend_1",server="192.168.1.146:80"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_upstream_server_received{upstream="backend_1",server="192.168.1.11:80"} = 0
2021-12-02T13:00:59.694214367Z nginxplus_upstream_server_requests{upstream="backend_1",server="192.168 [...]

2021-12-03 02:32 UTC, edsiper commented
can you try the output with `valgrind --leak-check=full` to get full visibility of the leaks ?

2021-12-03 15:17 UTC, pwhelan commented
> can you try the output with `valgrind --leak-check=full` to get full visibility of the leaks ?

```
valgrind --leak-check=full ./bin/fluent-bit -vvv -i nginx_metrics -p host=172.17.0.2 -p port=80 -p nginx_plus=on -p status_url=/api/ -o stdout -m '*' -f 1
==78994== Memcheck, a memory error detector
==78994== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==78994== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==78994== Command: ./bin/fluent-bit -vvv -i nginx_metrics -p host=172.17.0.2 -p port=80 -p nginx_plus=on -p status_url=/api/ -o stdout -m * -f 1
==78994== 
Fluent Bit v1.9.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/12/03 12:15:27] [ info] Configuration:
[2021/12/03 12:15:27] [ info]  flush time     | 1.000000 seconds
[2021/12/03 12:15:27] [ info]  grace          | 5 seconds
[2021/12/03 12:15:27] [ info]  daemon         | 0
[2021/12/03 12:15:27] [ info] ___________
[2021/12/03 12:15:27] [ info]  inputs:
[2021/12/03 12:15:27] [ info]      nginx_metrics
[2021/12/03 12:15:27] [ info] ___________
[2021/12/03 12:15:27] [ info]  filters:
[2021/12/03 12:15:27] [ info] ___________
[2021/12/03 12:15:27] [ info]  outputs:
[2021/12/03 12:15:27] [ info]      stdout.0
[2021/12/03 12:15:27] [ info] ___________
[2021/12/03 12:15:27] [ info]  collectors:
[2021/12/03 12:15:27] [ info] [engine] started (pid=78994)
[2021/12/03 12:15:27] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2021/12/03 12:15:27] [debug] [storage] [cio stream] new stream registered: nginx_metrics.0
[2021/12/03 12:15:27] [ info] [storage] version=1.1.5, initializing...
[2021/12/03 12:15:27] [ info] [storage] in-memory
[2021/12/03 12:15:27] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/12/03 12:15:27] [ info] [cmetrics] version=0.2.2
[2021/12/03 12:15:27] [ info] [input:nginx_metrics:nginx_metrics.0] nginx-plus mode on
[2021/12/03 12:15:27] [debug] [stdout:stdout.0] created event channels: read=19 write=20
[2021/12/03 12:15:27] [debug] [router] match rule nginx_metrics.0:stdout.0
[2021/12/03 12:15:27] [ info] [sp] stream processor started
[2021/12/03 12:15:28] [debug] [http_client] not using http_proxy for header
[2021/12/03 12:15:28] [debug] [upstream] KA connection #25 to 172.17.0.2:80 is now available
[2021/12/03 12:15:28] [debug] [upstream] KA connection #25 to 172.17.0.2:80 has been assigned (recycled)
[2021/12/03 12:15:28] [debug] [http_client] not using http_proxy for header
[2021/12/03 12:15:28] [debug] [upstream] KA connection #25 to 172.17.0.2:80 is now available
[2021/12/03 12:15:28] [debug] [upstream] KA connection #25 to 172.17.0.2:80 has been assigned (recycled)
[2021/12/03 12:15:28] [debug] [http_client] not using http_proxy for header
[2021/12/03 12:15:28] [debug] [upstream] KA connection #25 to 172.17.0.2:80 is now available
[2021/12/03 12:15:28] [debug] [upstream] KA connection #25 to 172.17.0.2:80 has been assigned (recycled)
[2021/12/03 12:15:28] [debug] [http_client] not using http_proxy for header
[2021/12/03 12:15:28] [debug] [upstream] KA connection #25 to 172.17.0.2:80 is now available
[2021/12/03 12:15:28] [debug] [upstream] KA connection #25 to 172.17.0.2:80 has been assigned (recycled)
[2021/12/03 12:15:28] [debug] [http_client] not using http_proxy for header
[2021/12/03 12:15:28] [debug] [upstream] KA connection #25 to 172.17.0.2:80 is now available
[2021/12/03 12:15:28] [debug] [upstream] KA connection #25 to 172.17.0.2:80 has been assigned (recycled)
[2021/12/03 12:15:28] [debug] [http_client] not using http_proxy for header
[2021/12/03 12:15:28] [debug] [upstream] KA connection #25 to 172.17.0.2:80 is now available
[2021/12/03 12:15:28] [debug] [upstream] KA connection #25 to 172.17.0.2:80 has been assigned (recycled)
[2021/12/03 12:15:28] [debug] [http_client] not using http_proxy for header
[2021/12/03 12:15:28] [debug] [upstream] KA connection #25 to 172.17.0.2:80 is now available
[2021/12/03 12:15:28] [debug] [upstream] KA connection #25 to 172.17.0.2:80 has been assigned (recycled)
[2021/12/03 12:15:28] [debug] [http_client] not using http_proxy for header
[2021/12/03 12:15:28] [debug] [upstream] KA connection #25 to 172.17.0.2:80 is now available
[2021/12/03 12:15:28] [debug] [upstream] KA connection #25 to 172.17.0.2:80 has been assigned (recycled)
[2021/12/03 12:15:28] [debug] [http_client] not using http_proxy for header
[2021/12/03 12:15:28] [debug] [upstream] KA connection #25 to 172.17.0.2:80 is now available
[2021/12/03 12:15:28] [debug] [input] destroy input_thread id=0
2021-12-03T15:15:28.229155249Z nginxplus_connections_accepted = 1
2021-12-03T15:15:28.229155249Z nginxplus_connections_dropped = 0
2021-12-03T15:15:28.229155249Z nginxplus_connections_active = 1
2021-12-03T15:15:28.229155249Z nginxplus_connections_idle = 0
2021-12-03T15:15:28.229155249Z nginxplus_ssl_handshakes = 0
2021-12-03T15:15:28.229155249Z nginxplus_ssl_handshakes_failed = 0
2021-12-03T15:15:28.229155249Z nginxplus_ssl_session_reuses = 0
2021-12-03T15:15:28.229155249Z nginxplus_http_requests_total = 4
2021-12-03T15:15:28.229155249Z nginxplus_http_requests_current = 1
2021-12-03T15:15:28.229155249Z nginxplus_server_zone_discarded{server_zone="thezone"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_server_zone_processing{server_zone="thezone"} = 1
2021-12-03T15:15:28.229155249Z nginxplus_server_zone_received{server_zone="thezone"} = 285
2021-12-03T15:15:28.229155249Z nginxplus_server_zone_requests{server_zone="thezone"} = 5
2021-12-03T15:15:28.229155249Z nginxplus_server_zone_responses{server_zone="thezone",code="1xx"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_server_zone_responses{server_zone="thezone",code="2xx"} = 4
2021-12-03T15:15:28.229155249Z nginxplus_server_zone_responses{server_zone="thezone",code="3xx"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_server_zone_responses{server_zone="thezone",code="4xx"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_server_zone_responses{server_zone="thezone",code="5xx"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_server_zone_sent{server_zone="thezone"} = 1017
2021-12-03T15:15:28.229155249Z nginxplus_server_zone_discarded{location_zone="dangerzone"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_location_zone_received{location_zone="dangerzone"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_location_zone_requests{location_zone="dangerzone"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_location_zone_responses{location_zone="dangerzone",code="1xx"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_location_zone_responses{location_zone="dangerzone",code="2xx"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_location_zone_responses{location_zone="dangerzone",code="3xx"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_location_zone_responses{location_zone="dangerzone",code="4xx"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_location_zone_responses{location_zone="dangerzone",code="5xx"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_location_zone_sent{location_zone="dangerzone"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_upstream_server_fails{upstream="backend_1",server="192.168.1.146:80"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_upstream_server_fails{upstream="backend_1",server="192.168.1.11:80"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_upstream_server_received{upstream="backend_1",server="192.168.1.146:80"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_upstream_server_received{upstream="backend_1",server="192.168.1.11:80"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_upstream_server_requests{upstream="backend_1",server="192.168.1.146:80"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_upstream_server_requests{upstream="backend_1",server="192.168.1.11:80"} = 0
2021-12-03T15:15:28.229155249Z nginxplus_upstream_server_responses{code="backend_1",upstream="192.168.1.146:80",server="1xx"} = 0
2021-12-03T15:15:28.229 [...]

2022-01-06 19:12 UTC, merged