build: Bundle fluent-bit-win32.conf only in Windows installers
fluent/fluent-bit pull request #4679
Opened 2022-01-24 23:46 UTC by fujimotos

This patch is a minor follow-up for f4e00e853, applying suggestions
by Jorge Niedbalski.

Since this file is intended for Windows platforms, we don't have to
include it to Unix packages

Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>

2022-01-25 09:49 UTC, patrick-stephens commented
Does this make the Windows installer completely functional out of the box? We should have a working default so just want to check that. My cmake is a bit rusty but this does not seem to change the defaults but just install the config file. 
I think we need a follow up change to make the Windows default to using this config file in some way, e.g. overwrite the default config file for Windows with this one (there's no point installing config files that won't work) or change the parameters for launching Fluent Bit so they use this one.

2022-01-25 10:24 UTC, niedbalski requested changes

2022-01-25 10:24 UTC, niedbalski commented on src/CMakeLists.txt
> +      "${PROJECT_SOURCE_DIR}/conf/fluent-bit-win32.conf"
Is there a reason on why this configuration can't be the default on windows systems? ${FLB_OUT_NAME}.conf?

2022-01-25 14:46 UTC, patrick-stephens commented
Looks great to me so happy to merge if you are @niedbalski

2022-01-26 10:54 UTC, niedbalski commented
LGTM

2022-01-26 10:54 UTC, niedbalski approved these changes

2022-01-26 10:54 UTC, merged