out_cloudwatch_logs: Only create log group if it does not already exist
fluent/fluent-bit pull request #4827
Opened 2022-02-15 08:21 UTC by PettitWesley

See: https://github.com/fluent/fluent-bit/pull/4826

Signed-off-by: Wesley Pettit <wppttt@amazon.com>

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2022-02-16 21:41 UTC, matthewfala approved these changes
LGTM

2022-02-16 21:44 UTC, matthewfala requested changes
Build failing on 1.8 for this diff?

2022-03-01 04:45 UTC, PettitWesley commented
@edsiper  I actually don't have power to merge my own PR on master even if it passes all checks
<img width="1236" alt="Screen Shot 2022-02-28 at 8 43 54 PM" src="https://user-images.githubusercontent.com/29443996/156106306-1c7cdeac-700c-4501-8e5b-2d83eee049f1.png">

CC @agup006 @nokute78

2022-03-04 22:39 UTC, nokute78 commented
@PettitWesley @edsiper I also can't merge it.

In this case, the PR was updated after approving.
Currently no one approves and it may prevent merging.

2022-04-05 00:58 UTC, edsiper commented
there is a code conflict:

```
plugins/out_cloudwatch_logs/cloudwatch_api.c
```

2022-04-19 19:08 UTC, merged