build: enable in_kafka and out_kafka by default
fluent/fluent-bit pull request #5204
Opened 2022-03-28 13:40 UTC by tarruda

close #5189

Signed-off-by: Thiago Padilha <thiago@calyptia.com>

2022-04-01 19:43 UTC, tarruda commented
@agup006 I've enabled kafka plugins by default, but not on Windows since it causes a build error on CI

2022-04-05 22:25 UTC, patrick-stephens commented
What's the build error?

2022-04-06 20:01 UTC, patrick-stephens commented
> What's the build error? 

Looks like it doesn't like some of the void* usage: https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/43155542/job/yyye570bjrb67uvg#L2827

2022-04-06 22:07 UTC, tarruda commented
Fixed the issue with windows build, just replacing `offsetof` by `container_of` macro took care of windows incompatibility

2022-04-07 08:21 UTC, patrick-stephens approved these changes
LGTM @niedbalski

2023-04-25 22:08 UTC, Boojapho commented
@edsiper @fujimotos @koleini @leonardo-albertovich, could we get this reviewed/merged so the next release will have the kafka plugins enabled by default?

2023-04-26 09:10 UTC, patrick-stephens commented
Currently there are merge conflicts, @tarruda can you resolve?

2023-04-26 09:31 UTC, patrick-stephens commented
We also need docs to resolve #7269

2023-04-26 11:48 UTC, tarruda commented
@patrick-stephens rebased.

2023-04-26 12:52 UTC, patrick-stephens commented
@tarruda please disable for Windows if it does not compile: https://github.com/fluent/fluent-bit/blob/master/cmake/windows-setup.cmake

2023-04-26 17:56 UTC, tarruda commented
@patrick-stephens rebased and fixed the builds. Couldn't enable by default on windows because the build fails on missing `libcrypto`, which I assume is a librdkafka dependency.

2023-05-16 14:48 UTC, leonardo-albertovich requested changes

2023-05-16 14:48 UTC, leonardo-albertovich commented on CMakeLists.txt
> +option(FLB_OUT_KAFKA                   "Enable Kafka output plugin"                   ${FLB_KAFKA_ENABLE_DEFAULT})
This should be a plain `Yes`

2023-05-16 14:48 UTC, leonardo-albertovich commented on CMakeLists.txt
> +option(FLB_IN_KAFKA                    "Enable Kafka input plugin"                    ${FLB_KAFKA_ENABLE_DEFAULT})
This should be a plain `Yes`

2023-05-16 14:48 UTC, leonardo-albertovich commented on CMakeLists.txt
> +if(FLB_SYSTEM_WINDOWS)
The conditional disable should be done in the [windows specific cmake file](https://github.com/fluent/fluent-bit/blob/master/cmake/windows-setup.cmake#L6)

2023-05-16 14:49 UTC, leonardo-albertovich commented
These changes are a hard requirement for this PR to be merged.

2023-05-16 15:03 UTC, leonardo-albertovich approved these changes

2023-05-16 16:37 UTC, tarruda commented
@leonardo-albertovich nevermind, it was a typo in windows-setup.cmake. Can you approve again?

2023-05-16 17:11 UTC, leonardo-albertovich approved these changes

2023-06-01 02:03 UTC, merged