csv: Implement CSV support library
fluent/fluent-bit pull request #5269
Opened 2022-04-08 14:13 UTC by tarruda

This implements a CSV library that can be used as the basis of implementing CSV plugins/parsers on fluent-bit.

The library is designed with a simple re-entrant API where you feed bytes, and the parse function tells you if it needs more data to complete a full CSV record. 

It can optionally receive a callback that will be invoked whenever a CSV column is fully parsed (idea similar to a SAX parser). If no callback is passed, then the library can only be used for splitting CSV records (which may span across multiple lines).

A note about the tests: It may seem complex, but I've tested the same inputs multiple times, with each time having a different chunk size (from 1 to the full data). The reason for doing this is that we can't predict where CSV data will be split when reading from a file descriptor, so it is important to test every possible way the input can be fed.

Also did some fixes for the flb_file.c module, which was not properly creating a NUL terminated `flb_sds_t` instance.

2022-04-08 21:41 UTC, edsiper requested changes

2022-04-08 21:41 UTC, edsiper commented on include/fluent-bit/flb_csv.h
> +        struct flb_csv_state *state,
please align parameters to the `(` level

2022-04-08 21:41 UTC, edsiper commented on src/flb_csv.c
> +        struct flb_csv_state *state,
please align parameters to the `(` level

2022-04-08 21:41 UTC, edsiper commented on src/flb_csv.c
> +        struct flb_csv_state *state,
please align parameters to the `(` level

2022-04-08 21:41 UTC, edsiper commented on src/flb_csv.c
> +        struct flb_csv_state *state,
please align parameters to the `(` level

2022-04-08 21:41 UTC, edsiper commented on src/flb_csv.c
> +        struct flb_csv_state *state,
please align parameters to the `(` level

2022-04-08 21:41 UTC, edsiper commented on src/flb_csv.c
> +        struct flb_csv_state *state,
please align parameters to the `(` level

2022-04-08 21:41 UTC, edsiper commented on src/flb_csv.c
> +            } else if (c == '\n') {
`else if` must go in the next line: https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#general-requirements

2022-04-08 21:41 UTC, edsiper commented on src/flb_csv.c
> +            } else if (c == ',') {
https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#general-requirements

2022-04-08 21:41 UTC, edsiper commented on src/flb_csv.c
> +        } else if (state->state == FLB_CSV_STATE_FOUND_CR) {
https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#general-requirements

2022-04-10 17:56 UTC, tarruda commented
fixed the style errors

2022-04-19 03:24 UTC, merged