tests: internal: fuzzers: fix index error
fluent/fluent-bit pull request #5602
Opened 2022-06-21 14:05 UTC by DavidKorczynski

Fixes wrong indices used for array indexing.

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45911

Signed-off-by: David Korczynski <david@adalogics.com>

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [N/A] Debug log output from testing the change

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2022-06-24 23:47 UTC, nokute78 requested changes

2022-06-24 23:47 UTC, nokute78 commented on tests/internal/fuzzers/multiline_fuzzer.c
> +		    /* stream_ids index by j, random_strings index by i */
Could you check indentation level ?

2022-06-25 01:16 UTC, DavidKorczynski commented on tests/internal/fuzzers/multiline_fuzzer.c
> +		    /* stream_ids index by j, random_strings index by i */
done

2022-07-05 15:13 UTC, DavidKorczynski commented
ping

2022-07-06 17:57 UTC, merged