parser: free allocated types
fluent/fluent-bit pull request #5608
Opened 2022-06-21 20:56 UTC by DavidKorczynski

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45973

Signed-off-by: David Korczynski <david@adalogics.com>

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [N/A] Debug log output from testing the change

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [N/A] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2022-06-24 23:32 UTC, nokute78 requested changes

2022-06-24 23:32 UTC, nokute78 commented on src/flb_parser.c
> +	    }
Could you check indentation level ?

2022-06-25 01:10 UTC, DavidKorczynski commented on src/flb_parser.c
> +	    }
done

2022-06-25 02:28 UTC, nokute78 approved these changes
Thank you. LGTM.

2022-06-27 22:24 UTC, merged