ra_key: Fix Segv on unknown address in flb_ra_translate
fluent/fluent-bit pull request #5727
Opened 2022-07-15 17:58 UTC by sashashura

This PR fixes Segv on unknown address in flb_ra_translate revealed by fuzzing:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46082

The root cause is that `flb_malloc` fails to allocate memory and because of that `flb_sds_create_len` constructs an invalid `flb_ra_value` with a type `MSGPACK_OBJECT_STR` in `msgpack_object_to_ra_value`.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2022-07-15 23:56 UTC, nokute78 requested changes
Thank you for contribution.

- Could you check DCO and modify it ?
   - https://probot.github.io/apps/dco/
- Could you check commit message style and modify it ? e.g. `ra_key: some message`
   - https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#commit-changes

2022-07-16 14:45 UTC, sashashura commented
Done. Please let me know if I did everything correctly.

2022-07-16 23:35 UTC, nokute78 commented
DCO is not fixed. Could you check it ?
https://github.com/fluent/fluent-bit/pull/5727/checks?check_run_id=7371207792

2022-07-17 13:28 UTC, sashashura commented
Done.

2022-07-18 00:24 UTC, nokute78 approved these changes
Thank you. LGTM.

2022-07-24 17:10 UTC, sashashura commented
Who can merge it?

2022-07-28 07:20 UTC, sashashura commented
@edsiper Could you please merge it?

2022-09-09 11:47 UTC, closed without merging

2022-09-09 11:57 UTC, sashashura commented
Fixed in https://github.com/fluent/fluent-bit/pull/5997