monkey: fix handling http requset crash
fluent/fluent-bit pull request #5940
Opened 2022-08-26 18:26 UTC by pluto-junzeng

This patch fix a problem when upload zip exceeding a certain size.
The flb_realloc in http_conn_event (http_conn.c:56)  free request->uri.data memory, fluent-bit crashed. 
Like issue #5532.

the patch have been tested using tools valgrind.

Signed-off-by:  Junzeng junzeng@mails.ccnu.edu.cn

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2022-08-30 13:33 UTC, tarruda requested changes
> The flb_realloc in http_conn_event (http_conn.c:56) free request->uri.data memory, fluent-bit crashed.

If flb_realloc tries to free `request->uri.data`, then simply changing it to `""` doesn't fix the problem, as you are passing a static address which also can't be freed.

Normally it is not a problem passing `NULL` to `realloc`. This is from man page:

```
 The realloc() function changes the size of the memory block pointed to by ptr to size bytes.  The contents will be unchanged in the range from the start of the region up to the minimum of the old
       and new sizes.  If the new size is larger than the old size, the added memory will not be initialized.  If ptr is NULL, then the call is equivalent to malloc(size), for all  values  of  size;
```

In other words, `realloc` doesn't try to free the argument passed as first argument if it is `NULL`.


Maybe something else is causing the crash. Can you paste the valgrind report here?

2022-08-30 16:12 UTC, leonardo-albertovich commented
I think there should be no side effects to this because `uri` is only set if the request is properly parsed and since it's a substring in the main request buffer it's not freed on its own, the only possible side effect would be in `mk_http_request_free` if the code doesn't pass through `mk_http_request_prepare` because `uri_processed` is set to `NULL` in `mk_http_request_init` which would cause the code to call `free` with `NULL` as argument (because it wouldn't match the constant used for `uri`).

Regardless of that, monkey patches have to be sent to its own [repository](https://github.com/monkey/monkey/), could you please do that instead?

2022-08-30 16:19 UTC, leonardo-albertovich commented
Sorry, my bad, I didn't properly read the original message. After doing so, I couldn't find a line where `free` is called with `request->uri.data` as argument but I did find line 364 in `http_prot.c` which dereferences the pointer in order to validate if the first character is a slash which would obviously cause a segmentation fault so I think even if @pluto-junzeng got it wrong the fix would work.

However I wonder why did `in_http` get to `http_prot_handle` after calling `mk_http_parser` and validating that its result was `MK_HTTP_PARSER_OK`. Something is wrong there. 

If there is a simple repro case we should verify it and determine what's the root cause because even though this seems to prevent the crash it doesn't address the re issue with the parser misrepresenting its state.

2022-08-31 15:11 UTC, pluto-junzeng commented
=678581== Invalid read of size 1
==678581==    at 0x203651: http_prot_handle (http_prot.c:364)
==678581==    by 0x201D73: http_conn_event (http_conn.c:98)
==678581==    by 0x19DB48: flb_engine_start (flb_engine.c:900)
==678581==    by 0x176943: flb_lib_worker (flb_lib.c:629)
==678581==    by 0x485C608: start_thread (pthread_create.c:477)
==678581==    by 0x4E71132: clone (clone.S:95)
==678581==  Address 0x4f9c1b5 is 5 bytes inside a block of size 512,000 free'd
==678581==    at 0x483DFAF: realloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==678581==    by 0x201848: flb_realloc (flb_mem.h:94)
==678581==    by 0x201A87: http_conn_event (http_conn.c:64)
==678581==    by 0x19DB48: flb_engine_start (flb_engine.c:900)
==678581==    by 0x176943: flb_lib_worker (flb_lib.c:629)
==678581==    by 0x485C608: start_thread (pthread_create.c:477)
==678581==    by 0x4E71132: clone (clone.S:95)
==678581==  Block was alloc'd at
==678581==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==678581==    by 0x2017F0: flb_malloc (flb_mem.h:79)
==678581==    by 0x20226A: http_conn_add (http_conn.c:237)
==678581==    by 0x2012C0: in_http_collect (http.c:54)
==678581==    by 0x184EAB: flb_input_collector_fd (flb_input.c:1749)
==678581==    by 0x19D779: flb_engine_handle_event (flb_engine.c:447)
==678581==    by 0x19D779: flb_engine_start (flb_engine.c:809)
==678581==    by 0x176943: flb_lib_worker (flb_lib.c:629)
==678581==    by 0x485C608: start_thread (pthread_create.c:477)
==678581==    by 0x4E71132: clone (clone.S:95)

2022-09-05 01:33 UTC, edsiper commented
NOTE: We need to fix the problem that this PR aims to address for v1.9 and the upcoming v2.0 series. 

cc: @lecaros

2023-01-19 14:06 UTC, closed without merging