ra_key: handle error case
fluent/fluent-bit pull request #5997
Opened 2022-09-04 16:54 UTC by DavidKorczynski

flb_sds_create_len may fail and this needs to be handled.

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46082

Signed-off-by: David Korczynski <david@adalogics.com>

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A ] Example configuration file for the change
- [N/A ] Debug log output from testing the change

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [N/A ] Documentation required for this feature

**Backporting**

- [N/A ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2022-09-05 01:21 UTC, edsiper requested changes

2022-09-05 01:21 UTC, edsiper commented on src/flb_ra_key.c
> +          return -1;
please align to 4 spaces as indentation

2022-09-05 11:53 UTC, DavidKorczynski commented on src/flb_ra_key.c
> +          return -1;
Done!

2022-09-05 14:14 UTC, merged

2022-09-09 11:47 UTC, sashashura commented
I'm confused why [my pull request](https://github.com/fluent/fluent-bit/pull/5727) with exactly same fix was ignored for so long.