in_opentelemetry: use ctraces to decode binary payload
fluent/fluent-bit pull request #6180
Opened 2022-10-11 06:20 UTC by Syn3rman

- Use ctraces to decode binary payload
- add config option for `raw_traces` that decides whether to process or forward traces

Signed-off-by: Aditya Prajapati <aditya@calyptia.com>

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [x] Example configuration file for the change

```
[INPUT]
	name opentelemetry
	host 127.0.0.1
	port 4318
	raw_traces true

[OUTPUT]
	name stdout
	match *
```

- [x] Debug log output from testing the change
![image](https://user-images.githubusercontent.com/31011197/195010768-69baf22b-670a-49e0-9aaf-01749a09820c.png)

- [x] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found
https://pastebin.com/cyfC0DNS

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [x] Documentation required for this feature

https://github.com/fluent/fluent-bit-docs/pull/872

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2022-10-11 13:08 UTC, edsiper requested changes

2022-10-11 13:08 UTC, edsiper commented on plugins/in_opentelemetry/opentelemetry_prot.c
> +        // ctr_decode_opentelemetry_destroy(decoded_context);
isn't this leading to a memory leak ? decode_context is not been destroyed

2022-10-11 13:09 UTC, edsiper commented
make sure to include a valgrind output with --leak-check=full

2022-10-12 15:35 UTC, Syn3rman commented
@edsiper fixed and attached valgrind output

2022-10-20 14:39 UTC, merged