fix in tail rotation
fluent/fluent-bit pull request #6230
Opened 2022-10-18 08:58 UTC by alt-dima

Signed-off-by: alt-dima <dmitrii.altukhov@guesty.com>

I have a problem with in_tail. Seems like rotation handling working correctly, but error appears.
```
[2022/10/18 07:04:59] [error] [C:\src\plugins\in_tail\tail_file.c:1445 errno=0] No error
[2022/10/18 07:04:59] [error] [input:tail:tail.0] link_inode=562949954146799 cannot detect if file: C:\var\log\containers\rms-poco-web-7ddc48bfb6-9k54x_default_rms-poco-web-1ad967282dda16ee80fb7b7e49930874ca695d34c0b2e554e573fe1e76623bfd.log
[2022/10/18 07:04:59] [ info] [input:tail:tail.0] inode=2814749767831688 handle rotation(): C:\var\log\containers\rms-poco-web-7ddc48bfb6-9k54x_default_rms-poco-web-1ad967282dda16ee80fb7b7e49930874ca695d34c0b2e554e573fe1e76623bfd.log => C:\ProgramData\docker\containers\1ad967282dda16ee80fb7b7e49930874ca695d34c0b2e554e573fe1e76623bfd\1ad967282dda16ee80fb7b7e49930874ca695d34c0b2e554e573fe1e76623bfd-json.log
```
Will try to fix
https://github.com/fluent/fluent-bit/blob/master/plugins/in_tail/tail_file.c#L1439
`if (errno == ENOENT) {` to `if (errno == ENOENT || errno == 0) {`

Yes! It helped, now looks good
```
│ [2022/10/18 08:12:45] [ info] [input:tail:tail.0] inode=844424930857462 link_rotated: C:\var\log\containers\rms-poco-web-7ddc48bfb6-qrwl8_default_rms-poco-web-1f6667f77f3a2b51d6eae45f0f22bb24e15c55c79ddbda0faa99740d4dc0ce87.log                      │
│ [2022/10/18 08:12:45] [ info] [input:tail:tail.0] inode=562949954146808 handle rotation(): C:\var\log\containers\rms-poco-web-7ddc48bfb6-qrwl8_default_rms-poco-web-1f6667f77f3a2b51d6eae45f0f22bb24e15c55c79ddbda0faa99740d4dc0ce87.log => C:\ProgramData\docker\containers\1f6667f77f3a2b51d6eae45f0f22bb24e15c55c79ddbda0faa99740d4dc0ce87\1f6667f77f3a2b51d6eae45f0f22bb24e15c55c79ddbda0faa99740d4dc0ce87-json.log 
```

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2022-10-24 09:38 UTC, leonardo-albertovich requested changes
For various reasons including the lack of `lstat` in windows this plugin uses a compatibility layer which should be the one emulating the `errno` state. 

Although this change does alleviate the symptom it could introduce a side effect in other platforms.

In order to avert this, could you please instead modify `win32_lstat`, `win32_stat` and `win32_fstat` in  `/plugins/in_tail/win32/stat.c` so they reset `errno` when entering and then set it to the appropriate value if they return through an error path?

Thank you.

2022-11-10 21:52 UTC, edsiper commented
@alt-dima would you please adjust the code with the suggested changes ?

2022-11-11 08:21 UTC, leonardo-albertovich commented
@alt-dima I just noticed your reaction, sorry but it wasn't there when I started my day. 
Please let us know if you want to adapt your PR to do what I did in mine so attribution is more direct. I only made it as a fallback in case you didn't answer and I would rather have you as the author instead of a mention in the PR message.

2022-11-11 08:43 UTC, alt-dima commented
@leonardo-albertovich Just checked your PR! Sorry, I'm not a developer and could never do the way you do!
I will close this PR, any mentions of me are not so important as work, that you can and do!
thank you!

2022-11-11 08:44 UTC, closed without merging

2022-11-11 08:54 UTC, leonardo-albertovich commented
Thanks a lot for investigating the issue, please let us know if you run into any issues once we release the fix.