trace: add new command line options for enabling tracing at startup.
fluent/fluent-bit pull request #6726
Opened 2023-01-24 15:51 UTC by pwhelan

Add new command line options to enable tracing from the start:
    
* --trace: define a complete trace pipeline in a single line.
* --trace-input: define the input to trace.
* --trace-output: define the trace output.
* --trace-output-property: define a trace output property.

The format for the `--trace` option is  the following:

```input=$INPUT_NAME output=$OUTPUT_PLUGIN output.$PROPERTY=$VALUE```

Several properties can be defined for the output plugin. Support for spaces in property values is not supported yet...

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2023-05-23 06:09 UTC, Syn3rman requested changes
I've added a few comments and requested a few changes. We are ignoring the return values from all the functions and while I have pointed out only one instance, we do need to check it everywhere.

2023-05-23 06:09 UTC, Syn3rman commented on src/fluent-bit.c
> +    flb_kv_item_create_len(props,
I don't see a corresponding destroy for this, are we sure this is being cleaned up properly?

2023-05-23 08:37 UTC, leonardo-albertovich commented
@pwhelan please let me know once you have addressed these requests widely in the code.

I've noticed many places where the results are not being checked but it makes no sense to point anything out before you have a chance to go over your changes and fix it.

2023-05-23 14:29 UTC, pwhelan commented on src/fluent-bit.c
> +            set_trace_property(trace_props, optarg);
I've add error checking to all the functions now.

2023-05-23 15:39 UTC, pwhelan commented
Valgrind log:

```bash
==611685== Memcheck, a memory error detector
==611685== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==611685== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==611685== Command: ./bin/fluent-bit -Z -i dummy -o exit -p flush_count=5 -f 1 --trace=input=dummy.0\ output=null
==611685== Parent PID: 563866
==611685== 
==611685== 
==611685== HEAP SUMMARY:
==611685==     in use at exit: 0 bytes in 0 blocks
==611685==   total heap usage: 3,280 allocs, 3,280 frees, 4,246,283 bytes allocated
==611685== 
==611685== All heap blocks were freed -- no leaks are possible
==611685== 
==611685== For lists of detected and suppressed errors, rerun with: -s
==611685== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

2023-07-17 16:22 UTC, pwhelan commented
Here is a valgrind log after the latest changes:

```
==31986== Memcheck, a memory error detector
==31986== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==31986== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==31986== Command: ./bin/fluent-bit -Z -i dummy -o stdout -m * -o exit -m * -p flush_count=5 -f 1 --trace=input=dummy.0\ output=null
==31986== Parent PID: 2603
==31986== 
==31986== 
==31986== HEAP SUMMARY:
==31986==     in use at exit: 0 bytes in 0 blocks
==31986==   total heap usage: 3,637 allocs, 3,637 frees, 4,916,409 bytes allocated
==31986== 
==31986== All heap blocks were freed -- no leaks are possible
==31986== 
==31986== For lists of detected and suppressed errors, rerun with: -s
==31986== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

2023-07-20 14:24 UTC, edsiper commented
@pwhelan do you have a PR for docs ?

2023-07-20 22:55 UTC, pwhelan commented
> do you have a PR for docs ?

@edsiper not yet, open one ASAP.

2023-07-21 19:43 UTC, merged