out_loki: add missing flb_sds_cat for float value
fluent/fluent-bit pull request #6834
Opened 2023-02-12 03:00 UTC by nokute78

out_loki doesn't append floating point value using following configuration.
```
[INPUT]
    Name dummy
    Dummy {"value":1.3}

[OUTPUT]
    Name loki
    Match *
    Line_Format key_value
```

```
$ nc -l 3100
POST /loki/api/v1/push HTTP/1.1
Host: 127.0.0.1:3100
Content-Length: 89
User-Agent: Fluent-Bit
Content-Type: application/json

{"streams":[{"stream":{"job":"fluent-bit"},"values":[["1676170056677523154","value="]]}]}^C
```

This patch is to fix it.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [X] Example configuration file for the change
- [X] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [N/A] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [N/A] Backport to latest stable release.

## Configuration 

```
[INPUT]
    Name dummy
    Dummy {"value":1.3}

[OUTPUT]
    Name loki
    Match *
    Line_Format key_value
```

## Debug/Valgrind output

```
$ valgrind --leak-check=full bin/flb-rt-out_loki 
==51995== Memcheck, a memory error detector
==51995== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==51995== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==51995== Command: bin/flb-rt-out_loki
==51995== 
Test remove_keys_remove_map...                  [ OK ]
Test labels_ra...                               [ OK ]
Test remove_keys...                             [ OK ]
Test basic...                                   [ OK ]
Test labels...                                  [ OK ]
Test label_keys...                              [ OK ]
Test line_format...                             [ OK ]
Test label_map_path...                          [ OK ]
Test float_value...                             [ OK ]
SUCCESS: All unit tests have passed.
==51995== 
==51995== HEAP SUMMARY:
==51995==     in use at exit: 0 bytes in 0 blocks
==51995==   total heap usage: 13,002 allocs, 13,002 frees, 6,006,621 bytes allocated
==51995== 
==51995== All heap blocks were freed -- no leaks are possible
==51995== 
==51995== For lists of detected and suppressed errors, rerun with: -s
==51995== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2023-02-12 05:42 UTC, nokute78 commented
Windows CI failed.
However it didn't relate this PR.

```
Invoke-WebRequest : ServerBusyEgress is over the account limit. RequestId:fa7ab4fe-401e-000a-228e-3e86d2000000 Time:2023-02-12T03:00:37.7618230Z
At line:1 char:1
+ Invoke-WebRequest -O winflexbison.zip $env:winflexbison
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
Command executed with exception: The remote server returned an error: (503) Server Unavailable.
```

2023-02-23 00:12 UTC, nokute78 commented
If #6902 is merged, this patch needs to be updated.

2023-02-28 15:58 UTC, leonardo-albertovich requested changes
Sorry, I didn't realize that this needed to be updated.

2023-03-02 11:21 UTC, nokute78 commented
I updated this PR.

From `safe_sds_cat(&buf, temp, len);` to `safe_sds_cat(buf, temp, len);` to following #6902

2023-03-02 11:23 UTC, leonardo-albertovich approved these changes

2023-03-02 11:24 UTC, leonardo-albertovich commented
Do you want to backport this to 2.0 or would you rather have me do it for you?

2023-03-02 11:38 UTC, nokute78 commented
@leonardo-albertovich I'll create a PR if #6926 will be merged.

2023-03-02 11:47 UTC, leonardo-albertovich commented
Once CI finishes I'll merge this so feel free to create it and edit the title later afterwards to reflect that it is indeed a backport or I'll do it, that way CI will run in parallel and we'll be done with it sooner.

2023-03-02 12:21 UTC, merged

2023-03-02 12:32 UTC, nokute78 commented
@leonardo-albertovich This patch depends on #6902 .
Because this patch is to append `safe_sds_cat` and first arg will be changed after merging.

So I think CI should run after merging #6926 to test with correct argument.

2023-03-02 12:57 UTC, nokute78 commented
@leonardo-albertovich Thank you for merging.
I created #6941 6941