sds: fix off by 1 bug in flb_sds_printf
fluent/fluent-bit pull request #7146
Opened 2023-04-08 04:39 UTC by PettitWesley

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2023-04-08 15:45 UTC, leonardo-albertovich requested changes
Please fix line 438 as instructed in the linked issue.

2023-04-10 16:47 UTC, edsiper commented
@PettitWesley ref: https://github.com/fluent/fluent-bit/issues/7143#issuecomment-1500915078

pls check the notes in the link above, let's prioritize the fix so we can include it

2023-04-10 17:35 UTC, PettitWesley commented
I will add unit test for this bug as well

2023-04-10 18:41 UTC, PettitWesley commented
@edsiper @leonardo-albertovich I updated and added a unit test that repros the change

2023-04-10 19:49 UTC, leonardo-albertovich approved these changes

2023-04-11 16:49 UTC, merged