in_windows_exporter_metrics: Implement WMI based memory and paging_file metrics
fluent/fluent-bit pull request #7817
Opened 2023-08-10 05:37 UTC by cosmo0920

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [x] Example configuration file for the change

These metrics can used as:
```powershell
PS> bin/fluent-bit -i windows_exporter_metrics -pmetrics=memory -pscrape_interval=2 -o stdout -vv
PS> bin/fluent-bit -i windows_exporter_metrics -pmetrics=paging_file -pscrape_interval=2 -o stdout
```
- [x] Debug log output from testing the change
```console
PS> bin/fluent-bit -i windows_exporter_metrics -pmetrics=paging_file -pscrape_interval=2 -o stdout -v
Fluent Bit v2.1.9
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/08/10 14:35:35] [ info] Configuration:
[2023/08/10 14:35:35] [ info]  flush time     | 1.000000 seconds
[2023/08/10 14:35:35] [ info]  grace          | 5 seconds
[2023/08/10 14:35:35] [ info]  daemon         | 0
[2023/08/10 14:35:35] [ info] ___________
[2023/08/10 14:35:35] [ info]  inputs:
[2023/08/10 14:35:35] [ info]      windows_exporter_metrics
[2023/08/10 14:35:35] [ info] ___________
[2023/08/10 14:35:35] [ info]  filters:
[2023/08/10 14:35:35] [ info] ___________
[2023/08/10 14:35:35] [ info]  outputs:
[2023/08/10 14:35:35] [ info]      stdout.0
[2023/08/10 14:35:35] [ info] ___________
[2023/08/10 14:35:35] [ info]  collectors:
[2023/08/10 14:35:35] [ info] [fluent bit] version=2.1.9, commit=a792dcb821, pid=19160
[2023/08/10 14:35:35] [debug] [engine] coroutine stack size: 98302 bytes (96.0K)
[2023/08/10 14:35:35] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/08/10 14:35:35] [ info] [cmetrics] version=0.6.3
[2023/08/10 14:35:35] [ info] [ctraces ] version=0.3.1
[2023/08/10 14:35:35] [ info] [input:windows_exporter_metrics:windows_exporter_metrics.0] initializing
[2023/08/10 14:35:35] [ info] [input:windows_exporter_metrics:windows_exporter_metrics.0] storage_strategy='memory' (memory only)
[2023/08/10 14:35:35] [debug] [windows_exporter_metrics:windows_exporter_metrics.0] created event channels: read=856 write=860
[2023/08/10 14:35:35] [debug] [input:windows_exporter_metrics:windows_exporter_metrics.0] enabled metrics paging_file
[2023/08/10 14:35:35] [debug] [stdout:stdout.0] created event channels: read=1248 write=1232
[2023/08/10 14:35:35] [ info] [sp] stream processor started
[2023/08/10 14:35:35] [ info] [output:stdout:stdout.0] worker #0 started
[2023/08/10 14:35:37] [debug] [input:windows_exporter_metrics:windows_exporter_metrics.0] initializing WMI instance....
[2023/08/10 14:35:37] [debug] [input:windows_exporter_metrics:windows_exporter_metrics.0] deinitializing WMI instance....
[2023/08/10 14:35:37] [debug] [input chunk] update output instances with new chunk size diff=735, records=0, input=windows_exporter_metrics.0
[2023/08/10 14:35:38] [debug] [task] created task=000001F220B5CA60 id=0 OK
[2023/08/10 14:35:38] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
2023-08-10T05:35:37.505007700Z windows_paging_file_allocated_base_size_megabytes = 15889
2023-08-10T05:35:37.505007700Z windows_paging_file_current_usage_megabytes = 1013
2023-08-10T05:35:37.505007700Z windows_paging_file_peak_usage_megabytes = 1077
[2023/08/10 14:35:38] [debug] [out flush] cb_destroy coro_id=0
[2023/08/10 14:35:38] [debug] [task] destroy task=000001F220B5CA60 (task_id=0)
[2023/08/10 14:35:39] [debug] [input:windows_exporter_metrics:windows_exporter_metrics.0] initializing WMI instance....
[2023/08/10 14:35:39] [engine] caught signal (SIGINT)
[2023/08/10 14:35:39] [debug] [input:windows_exporter_metrics:windows_exporter_metrics.0] deinitializing WMI instance....
[2023/08/10 14:35:39] [debug] [input chunk] update output instances with new chunk size diff=735, records=0, input=windows_exporter_metrics.0
[2023/08/10 14:35:39] [debug] [task] created task=000001F220B5D0A0 id=0 OK
2023-08-10T05:35:39.503594100Z windows_paging_file_allocated_base_size_megabytes = 15889
2023-08-10T05:35:39.503594100Z windows_paging_file_current_usage_megabytes = 1013
2023-08-10T05:35:39.503594100Z windows_paging_file_peak_usage_megabytes = 1077
[2023/08/10 14:35:39] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[2023/08/10 14:35:39] [ warn] [engine] service will shutdown in max 5 seconds
[2023/08/10 14:35:39] [ info] [input] pausing windows_exporter_metrics.0
[2023/08/10 14:35:39] [debug] [out flush] cb_destroy coro_id=1
[2023/08/10 14:35:39] [debug] [task] destroy task=000001F220B5D0A0 (task_id=0)
[2023/08/10 14:35:40] [ info] [engine] service has stopped (0 pending tasks)
[2023/08/10 14:35:40] [ info] [input] pausing windows_exporter_metrics.0
[2023/08/10 14:35:40] [ info] [output:stdout:stdout.0] thread worker #0 stopping...
[2023/08/10 14:35:40] [ info] [output:stdout:stdout.0] thread worker #0 stopped
PS> bin/fluent-bit -i windows_exporter_metrics -pmetrics=memory -pscrape_interval=2 -o stdout -v
Fluent Bit v2.1.9
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/08/10 14:36:14] [ info] Configuration:
[2023/08/10 14:36:14] [ info]  flush time     | 1.000000 seconds
[2023/08/10 14:36:14] [ info]  grace          | 5 seconds
[2023/08/10 14:36:14] [ info]  daemon         | 0
[2023/08/10 14:36:14] [ info] ___________
[2023/08/10 14:36:14] [ info]  inputs:
[2023/08/10 14:36:14] [ info]      windows_exporter_metrics
[2023/08/10 14:36:14] [ info] ___________
[2023/08/10 14:36:14] [ info]  filters:
[2023/08/10 14:36:14] [ info] ___________
[2023/08/10 14:36:14] [ info]  outputs:
[2023/08/10 14:36:14] [ info]      stdout.0
[2023/08/10 14:36:14] [ info] ___________
[2023/08/10 14:36:14] [ info]  collectors:
[2023/08/10 14:36:14] [ info] [fluent bit] version=2.1.9, commit=a792dcb821, pid=32048
[2023/08/10 14:36:14] [debug] [engine] coroutine stack size: 98302 bytes (96.0K)
[2023/08/10 14:36:14] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/08/10 14:36:14] [ info] [cmetrics] version=0.6.3
[2023/08/10 14:36:14] [ info] [ctraces ] version=0.3.1
[2023/08/10 14:36:14] [ info] [input:windows_exporter_metrics:windows_exporter_metrics.0] initializing
[2023/08/10 14:36:14] [ info] [input:windows_exporter_metrics:windows_exporter_metrics.0] storage_strategy='memory' (memory only)
[2023/08/10 14:36:14] [debug] [windows_exporter_metrics:windows_exporter_metrics.0] created event channels: read=856 write=860
[2023/08/10 14:36:14] [debug] [input:windows_exporter_metrics:windows_exporter_metrics.0] enabled metrics memory
[2023/08/10 14:36:14] [debug] [stdout:stdout.0] created event channels: read=1224 write=1248
[2023/08/10 14:36:14] [ info] [sp] stream processor started
[2023/08/10 14:36:14] [ info] [output:stdout:stdout.0] worker #0 started
[2023/08/10 14:36:16] [debug] [input:windows_exporter_metrics:windows_exporter_metrics.0] initializing WMI instance....
[2023/08/10 14:36:18] [debug] [input:windows_exporter_metrics:windows_exporter_metrics.0] deinitializing WMI instance....
[2023/08/10 14:36:18] [debug] [input chunk] update output instances with new chunk size diff=8322, records=0, input=windows_exporter_metrics.0
[2023/08/10 14:36:18] [debug] [task] created task=000001464C3BCC30 id=0 OK
2023-08-10T05:36:16.419798800Z windows_memory_available_bytes = 2964451328
2023-08-10T05:36:16.419798800Z windows_memory_cache_bytes = 347045888
2023-08-10T05:36:16.419798800Z windows_memory_cache_bytes_peak = 759558144
2023-08-10T05:36:16.419798800Z windows_memory_cache_faults_total = 52215279
2023-08-10T05:36:16.419798800Z windows_memory_commit_limit = 33520226304
2023-08-10T05:36:16.419798800Z windows_memory_committed_bytes = 28709236736
2023-08-10T05:36:16.419798800Z windows_memory_demand_zero_faults_total = 512455022
2023-08-10T05:36:16.419798800Z windows_memory_free_and_zero_page_list_bytes = 36667392
2023-08-10T05:36:16.419 [...]

2023-08-10 10:13 UTC, leonardo-albertovich requested changes

2023-08-10 10:13 UTC, leonardo-albertovich commented on plugins/in_windows_exporter_metrics/we_wmi_paging_file.c
> +    struct cmt_gauge *g;
Move these and any other variable definitions to the beginning of the function

2023-08-10 10:13 UTC, leonardo-albertovich commented on plugins/in_windows_exporter_metrics/we_wmi_paging_file.c
> +        if(0 == ret) {
Invert this clause so it's `ret == 0`

2023-08-10 15:50 UTC, leonardo-albertovich approved these changes

2023-08-19 16:58 UTC, merged

2023-08-19 16:59 UTC, edsiper commented
@cosmo0920 is there a docs PR ? (cc: @lecaros )

2023-08-20 03:10 UTC, cosmo0920 commented
The corresponding doc PS is here(also it included in the description of the PR): https://github.com/fluent/fluent-bit-docs/pull/1176