tests: internal: stream_processor: fix when test path is too long.
fluent/fluent-bit pull request #7869
Opened 2023-08-25 14:30 UTC by pwhelan

# Summary

Fix the usage of datafile so it will not overflow when testing from a long repository path. This patch uses snprintf as well as defining the size of the string with PATH_MAX.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [N/A] Debug log output from testing the change

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [N/A] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2023-08-25 22:25 UTC, nokute78 requested changes
Could you check review comments ?

2023-08-25 22:25 UTC, nokute78 commented on tests/internal/stream_processor.c
> +                if (ret > sizeof(datafile)-1) {
These lines can be replaced like 
```c
if (!TEST_CHECK(ret <= sizeof(datafile)-1)) {
```

2023-08-25 22:25 UTC, nokute78 commented on tests/internal/stream_processor.c
> +            if (ret > sizeof(datafile)-1) {
Ditto

2023-08-29 10:05 UTC, edsiper commented
@pwhelan please fix the commit prefix, it should be `tests: internal: stream_processor: ...`

2023-08-29 15:21 UTC, pwhelan commented
> tests: internal: stream_processor

As requested.

2023-08-30 11:57 UTC, nokute78 approved these changes
LGTM.

2023-09-04 22:08 UTC, merged