in_calyptia_fleet: windows support.
fluent/fluent-bit pull request #7929
Opened 2023-09-15 14:51 UTC by pwhelan

# Summary

This PR implemenets hot reload in windows for the `in_calyptia_fleet` plugin. It includes the necessary changes for the plugin itself as well as rudimentary support for hot-reload under win32.

# Obstacles

The calyptia fleet plugin reloads configuration taken from calyptia, which requires hot-reload in windows. This requires two major changes:

- fixing TLS under windows: monkey/monkey#408.
- Simulating the SIGHUP signal.

## Solutions

### TLS

The first concern was fixed in monkey and is still awaiting merging upstream to fluent-bit.

### SIGHUP

I used GenerateConsoleCtrlEvent to simulate the behavior of the SIGHUP signal in windows and implemented a simple mechanism to signal the main thread from the GenerateConsoleCtrlEvent handler. This is so the main thread can execute flb_reload.

The implementation I went with uses a simple `int` to mark that the signal has been raised. The main  loop then checks it, marks it as zero and then executes `flb_reload`. This is, admittedly, functional but not elegant.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2023-09-15 15:09 UTC, edsiper requested changes

2023-09-15 15:09 UTC, edsiper commented on src/fluent-bit.c
> +	}
fix indentation level of `}`

2023-09-15 15:09 UTC, edsiper commented on src/fluent-bit.c
> +            /* signal the main loop to execute reload. this is necessary since
fix indentation

2023-09-18 16:48 UTC, pwhelan commented
There is still a blocker concerning the compile error on 32 bit windows which I have yet to resolve.

2023-09-18 16:58 UTC, patrick-stephens commented
> There is still a blocker concerning the compile error on 32 bit windows which I have yet to resolve.

This one? https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/48047875/job/ubcx7x6cxx26ftkj
That looks like the usual flaky test...
```
[ FAILED ]
  log.c:16: Check (*interval >= timeout - 1) && *interval <= timeout... failed
    interval error. got=3 expect=4-5
  log.c:92: Check ret == 0... failed
    update_and_check_interval for TEST_RECORD_01 failed. i=9
  log.c:16: Check (*interval >= timeout - 1) && *interval <= timeout... failed
    interval error. got=3 expect=4-5
  log.c:98: Check ret == 0... failed
    update_and_check_interval for TEST_RECORD_02 failed. i=9
Test cache_one_slot...                          
[ OK ]
FAILED: 1 of 2 unit tests has failed.
```

2023-09-18 17:22 UTC, pwhelan commented
It was failing on compile before. Seems like my last commit fixed it.

2023-09-18 18:06 UTC, edsiper commented
@pwhelan  I merged #7925 which generated some conflicts here, please fix the conflicts.

2023-09-20 14:41 UTC, pwhelan commented
The commit [59270d8](https://github.com/monkey/monkey/commit/59270d80bc68d8c01f21dd6d13c9da776cf3b5b0) from monkey still needs to be integrated before windows reload can work.

2023-09-21 14:26 UTC, merged