feat(out_loki): add compress option for gzip
fluent/fluent-bit pull request #7949
Opened 2023-09-20 09:51 UTC by ksauzz

Add compress option for gzip compression for out_loki

Fixes #7917

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [ ] Example configuration file for the change

Run loki

```
docker run --rm --net=host grafana/loki
```

fluentbit.conf

```
[INPUT]
    Name    dummy
    rate    60

[OUTPUT]
    Name     loki
    Match    *
    compress gzip

 ```

- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found
<details>
<summary>compress=gzip</summary>

```
% valgrind --leak-check=full ./bin/fluent-bit -c fluent.conf
==1447749== Memcheck, a memory error detector
==1447749== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==1447749== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==1447749== Command: ./bin/fluent-bit -c fluent.conf
==1447749== 
Fluent Bit v2.1.10
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/09/20 18:48:17] [ info] [fluent bit] version=2.1.10, commit=47b42dd4df, pid=1447749
[2023/09/20 18:48:17] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/09/20 18:48:17] [ info] [cmetrics] version=0.6.3
[2023/09/20 18:48:17] [ info] [ctraces ] version=0.3.1
[2023/09/20 18:48:17] [ info] [input:dummy:dummy.0] initializing
[2023/09/20 18:48:17] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2023/09/20 18:48:17] [ info] [output:loki:loki.0] configured, hostname=127.0.0.1:3100
[2023/09/20 18:48:17] [ info] [sp] stream processor started
^C[2023/09/20 18:48:24] [engine] caught signal (SIGINT)
[2023/09/20 18:48:24] [ warn] [engine] service will shutdown in max 5 seconds
[2023/09/20 18:48:24] [ info] [input] pausing dummy.0
[2023/09/20 18:48:25] [ info] [engine] service has stopped (0 pending tasks)
[2023/09/20 18:48:25] [ info] [input] pausing dummy.0
==1447749== 
==1447749== HEAP SUMMARY:
==1447749==     in use at exit: 0 bytes in 0 blocks
==1447749==   total heap usage: 6,123 allocs, 6,123 frees, 13,243,207 bytes allocated
==1447749== 
==1447749== All heap blocks were freed -- no leaks are possible
==1447749== 
==1447749== For lists of detected and suppressed errors, rerun with: -s
==1447749== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
</details>

<details>
<summary>disable gzip</summary>

```
% valgrind --leak-check=full ./bin/fluent-bit -c fluent.conf
==1450498== Memcheck, a memory error detector
==1450498== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==1450498== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==1450498== Command: ./bin/fluent-bit -c fluent.conf
==1450498== 
Fluent Bit v2.1.10
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/09/20 18:49:18] [ info] [fluent bit] version=2.1.10, commit=47b42dd4df, pid=1450498
[2023/09/20 18:49:18] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/09/20 18:49:18] [ info] [cmetrics] version=0.6.3
[2023/09/20 18:49:18] [ info] [ctraces ] version=0.3.1
[2023/09/20 18:49:18] [ info] [input:dummy:dummy.0] initializing
[2023/09/20 18:49:18] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2023/09/20 18:49:18] [ info] [output:loki:loki.0] configured, hostname=127.0.0.1:3100
[2023/09/20 18:49:18] [ info] [sp] stream processor started
^C[2023/09/20 18:49:32] [engine] caught signal (SIGINT)
[2023/09/20 18:49:32] [ warn] [engine] service will shutdown in max 5 seconds
[2023/09/20 18:49:32] [ info] [input] pausing dummy.0
[2023/09/20 18:49:33] [ info] [engine] service has stopped (0 pending tasks)
[2023/09/20 18:49:33] [ info] [input] pausing dummy.0
==1450498== 
==1450498== HEAP SUMMARY:
==1450498==     in use at exit: 0 bytes in 0 blocks
==1450498==   total heap usage: 10,179 allocs, 10,179 frees, 19,938,876 bytes allocated
==1450498== 
==1450498== All heap blocks were freed -- no leaks are possible
==1450498== 
==1450498== For lists of detected and suppressed errors, rerun with: -s
==1450498== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

</details>

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2023-09-20 11:56 UTC, ksauzz commented
Removed unnecessary changes.

2023-09-20 12:58 UTC, cosmo0920 requested changes
I added comments for the first impressions.

2023-09-20 12:58 UTC, cosmo0920 commented on plugins/out_loki/loki.c
> +                            FLB_LOKI_CE_GZIP, sizeof(FLB_LOKI_CE_GZIP) - 1);
We have a short-hand function to set up gzip content encoding type: [flb_http_set_content_encoding_gzip](https://github.com/fluent/fluent-bit/blob/e5f12f9161fdce8ea9edbd77afad298eb1bda733/src/flb_http_client.c#L1046)
Would you mind if you used the function here?

2023-09-20 12:58 UTC, cosmo0920 commented on plugins/out_loki/loki.c
> +          flb_free(out_buf);
Could you use 4-spaces indentation here?

2023-09-20 12:58 UTC, cosmo0920 commented on plugins/out_loki/loki.c
> +          flb_sds_destroy(out_buf);
ditto.

2023-09-20 12:58 UTC, cosmo0920 commented on plugins/out_loki/loki.c
> +      flb_free(out_buf);
ditto.

2023-09-20 12:58 UTC, cosmo0920 commented on plugins/out_loki/loki.c
> +      flb_sds_destroy(out_buf);
ditto.

2023-09-20 12:58 UTC, cosmo0920 commented on plugins/out_loki/loki.c
> +
Could you use one newline here? So, remove an additional newline, please?

2023-09-20 12:58 UTC, cosmo0920 commented on plugins/out_loki/loki.c
> +        flb_sds_destroy(out_buf);
Should we treat deallocations like as follows?

```c
if (compressed) {
    flb_free(out_buf);
}
else {
    flb_sds_destroy(out_buf);
}
```

2023-09-20 13:39 UTC, ksauzz commented
Thank you for the review. I pushed the changes.

<details><summary>with gzip</summary>

```
% valgrind  bin/fluent-bit -i dummy -p rate=60 -o loki -p match='*' -p labels="job=gzip" -p compress=gzip

==90770== Memcheck, a memory error detector
==90770== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==90770== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==90770== Command: bin/fluent-bit -i dummy -p rate=60 -o loki -p match=* -p labels=job=gzip -p compress=gzip
==90770== 
Fluent Bit v2.1.10
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/09/20 22:36:56] [ info] [fluent bit] version=2.1.10, commit=47b42dd4df, pid=90770
[2023/09/20 22:36:56] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/09/20 22:36:56] [ info] [cmetrics] version=0.6.3
[2023/09/20 22:36:56] [ info] [ctraces ] version=0.3.1
[2023/09/20 22:36:56] [ info] [input:dummy:dummy.0] initializing
[2023/09/20 22:36:56] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2023/09/20 22:36:56] [ info] [output:loki:loki.0] configured, hostname=127.0.0.1:3100
[2023/09/20 22:36:56] [ info] [sp] stream processor started
^C[2023/09/20 22:37:10] [engine] caught signal (SIGINT)
[2023/09/20 22:37:10] [ warn] [engine] service will shutdown in max 5 seconds
[2023/09/20 22:37:10] [ info] [input] pausing dummy.0
[2023/09/20 22:37:11] [ info] [engine] service has stopped (0 pending tasks)
[2023/09/20 22:37:11] [ info] [input] pausing dummy.0
==90770== 
==90770== HEAP SUMMARY:
==90770==     in use at exit: 0 bytes in 0 blocks
==90770==   total heap usage: 10,385 allocs, 10,385 frees, 24,903,131 bytes allocated
==90770== 
==90770== All heap blocks were freed -- no leaks are possible
==90770== 
==90770== For lists of detected and suppressed errors, rerun with: -s
==90770== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
```
% curl -G -s  "http://localhost:3100/loki/api/v1/query_range" --data-urlencode 'query={job="gzip"}' --data 'limit=2' | jq '.data.result' 
[
  {
    "stream": {
      "job": "gzip"
    },
    "values": [
      [
        "1695217030265459845",
        "{\"message\":\"dummy\"}"
      ],
      [
        "1695217030243066342",
        "{\"message\":\"dummy\"}"
      ]
    ]
  }
]
```

</details>


<details><summary>without gzip</summary>


```
% valgrind bin/fluent-bit -i dummy -p rate=60 -o loki -p match='*' -p labels="job=plain"                 

==89675== Memcheck, a memory error detector
==89675== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==89675== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==89675== Command: bin/fluent-bit -i dummy -p rate=60 -o loki -p match=* -p labels=job=plain
==89675== 
Fluent Bit v2.1.10
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/09/20 22:36:31] [ info] [fluent bit] version=2.1.10, commit=47b42dd4df, pid=89675
[2023/09/20 22:36:32] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/09/20 22:36:32] [ info] [cmetrics] version=0.6.3
[2023/09/20 22:36:32] [ info] [ctraces ] version=0.3.1
[2023/09/20 22:36:32] [ info] [input:dummy:dummy.0] initializing
[2023/09/20 22:36:32] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2023/09/20 22:36:32] [ info] [output:loki:loki.0] configured, hostname=127.0.0.1:3100
[2023/09/20 22:36:32] [ info] [sp] stream processor started
^C[2023/09/20 22:36:46] [engine] caught signal (SIGINT)
[2023/09/20 22:36:46] [ warn] [engine] service will shutdown in max 5 seconds
[2023/09/20 22:36:46] [ info] [input] pausing dummy.0
[2023/09/20 22:36:47] [ info] [engine] service has stopped (0 pending tasks)
[2023/09/20 22:36:47] [ info] [input] pausing dummy.0
==89675== 
==89675== HEAP SUMMARY:
==89675==     in use at exit: 0 bytes in 0 blocks
==89675==   total heap usage: 10,736 allocs, 10,736 frees, 21,130,607 bytes allocated
==89675== 
==89675== All heap blocks were freed -- no leaks are possible
==89675== 
==89675== For lists of detected and suppressed errors, rerun with: -s
==89675== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
```
% curl -G -s  "http://localhost:3100/loki/api/v1/query_range" --data-urlencode 'query={job="plain"}' --data 'limit=2' | jq '.data.result'
[
  {
    "stream": {
      "job": "plain"
    },
    "values": [
      [
        "1695217006259634558",
        "{\"message\":\"dummy\"}"
      ],
      [
        "1695217006242857311",
        "{\"message\":\"dummy\"}"
      ]
    ]
  }
]

```

</details>

2023-09-20 14:29 UTC, cosmo0920 commented
It looks great. Thanks for addressing my comments. I'll confirm this PR with the actual Loki and associated Grafana instances tomorrow.

2023-09-21 01:57 UTC, cosmo0920 commented
I confirmed that your PR is working as expected:

### Command

```console
% bin/fluent-bit -i dummy -o loki 
Fluent Bit v2.1.10
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/09/21 10:54:47] [ info] [fluent bit] version=2.1.10, commit=398f4346ae, pid=2472415
[2023/09/21 10:54:47] [ info] [storage] ver=1.1.6, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/09/21 10:54:47] [ info] [cmetrics] version=0.6.3
[2023/09/21 10:54:47] [ info] [ctraces ] version=0.3.1
[2023/09/21 10:54:47] [ info] [input:dummy:dummy.0] initializing
[2023/09/21 10:54:47] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2023/09/21 10:54:47] [ info] [output:loki:loki.0] configured, hostname=127.0.0.1:3100
[2023/09/21 10:54:47] [ info] [sp] stream processor started
^C[2023/09/21 10:54:50] [engine] caught signal (SIGINT)
[2023/09/21 10:54:50] [ warn] [engine] service will shutdown in max 5 seconds
[2023/09/21 10:54:50] [ info] [input] pausing dummy.0
[2023/09/21 10:54:51] [ info] [engine] service has stopped (0 pending tasks)
[2023/09/21 10:54:51] [ info] [input] pausing dummy.0
% bin/fluent-bit -i dummy -o loki -pcompress=gzip
Fluent Bit v2.1.10
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/09/21 10:54:52] [ info] [fluent bit] version=2.1.10, commit=398f4346ae, pid=2472520
[2023/09/21 10:54:52] [ info] [storage] ver=1.1.6, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/09/21 10:54:52] [ info] [cmetrics] version=0.6.3
[2023/09/21 10:54:52] [ info] [ctraces ] version=0.3.1
[2023/09/21 10:54:52] [ info] [input:dummy:dummy.0] initializing
[2023/09/21 10:54:52] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2023/09/21 10:54:52] [ info] [output:loki:loki.0] configured, hostname=127.0.0.1:3100
[2023/09/21 10:54:52] [ info] [sp] stream processor started
^C[2023/09/21 10:54:55] [engine] caught signal (SIGINT)
[2023/09/21 10:54:55] [ warn] [engine] service will shutdown in max 5 seconds
[2023/09/21 10:54:55] [ info] [input] pausing dummy.0
[2023/09/21 10:54:55] [ info] [engine] service has stopped (0 pending tasks)
[2023/09/21 10:54:55] [ info] [input] pausing dummy.0
```

### Result on Loki and associated Grafana instances

![Screenshot 2023-09-21 at 10-55-14 Explore - Loki - Grafana](https://github.com/fluent/fluent-bit/assets/700876/0790d0a2-c58c-4707-a975-63314cb13c2f)

2023-09-21 02:01 UTC, cosmo0920 approved these changes
Honestly speaking, I'm also writing for gzip compression patch. But, I love to use yours.
This approach looks better than mine. Thanks for your contribution. :+1:

2023-09-21 02:02 UTC, cosmo0920 requested changes
Oh, one thing. This patch looks great but the commit message does not follow our guideline.
So, could you use `out_loki: ... ` style instead of `feat(out_loki): ...`?

2023-09-21 02:11 UTC, cosmo0920 commented
Waiting for CI results... And thanks for the quick response. :muscle:

2023-09-21 02:12 UTC, ksauzz commented
Sorry for the overlap in tasks. I appreciate your help. :pray:

2023-09-21 02:20 UTC, cosmo0920 commented
No worries. Encouraging for new contributor is also important for us. :smile:

2023-09-21 03:13 UTC, cosmo0920 approved these changes

2023-09-21 04:10 UTC, merged

2023-09-21 04:10 UTC, edsiper commented
thank you!