aws_util: fix leading zeros in time_key
fluent/fluent-bit pull request #8116
Opened 2023-10-31 22:37 UTC by PettitWesley

Fixes #7538

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2023-11-02 22:59 UTC, nokute78 requested changes
How about using printf format like "%09" PRIu64 ?

2023-11-02 22:59 UTC, nokute78 commented on src/aws/flb_aws_util.c
> +    snprintf(nanosecond_str, FLB_AWS_NANOSECOND_LENGTH+1,
How about ensuring like following code ? 
```c
snprintf(nanosecond_str, FLB_AWS_NANOSECOND_LENGTH+1, "%09" PRIu64, (uint64_t) tms->tm.tv_nsec);
```

Example code:
```c
#include <stdio.h>
#include <inttypes.h>

int main()
{
  uint64_t val = 1;
  int i;

  for (i=0; i<9; i++)  {
    printf("i=%d " "%09" PRIu64 "\n", i, val);
    val *= 10;
  }
}
```

Output is 
```
i=0 000000001
i=1 000000010
i=2 000000100
i=3 000001000
i=4 000010000
i=5 000100000
i=6 001000000
i=7 010000000
i=8 100000000
```

2023-11-02 22:59 UTC, nokute78 commented on src/aws/flb_aws_util.c
> +    snprintf(millisecond_str, FLB_AWS_MILLISECOND_LENGTH+1,
How about ensuring like following code ?

snprintf(nanosecond_str, FLB_AWS_MILLISECOND_LENGTH+1, "%03" PRIu64, (uint64_t) tms->tm.tv_nsec / 1000000);

2023-11-07 03:33 UTC, edsiper commented
<img width="406" alt="image" src="https://github.com/fluent/fluent-bit/assets/369718/b5e3e759-9303-404b-a7d3-50017326d2eb">

2024-02-22 14:49 UTC, lecaros commented
ping @PettitWesley

2024-08-07 02:39 UTC, closed without merging

2024-08-07 02:43 UTC, edsiper commented
fixed in #9128