added-kusto-specific-headers
fluent/fluent-bit pull request #8360
Opened 2024-01-08 22:02 UTC by tanmaya-panda1

Signed-off-by: Tanmaya Panda <tanmayapanda@microsoft.com>
(cherry picked from commit ccfc8ee8bb261107b14c442b8687966ede4fd1bd)

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2024-01-10 20:17 UTC, edsiper requested changes

2024-01-10 20:17 UTC, edsiper commented on plugins/out_azure_kusto/azure_kusto_ingest.c
> +                //added kusto specific headers for debugging requests
please use /* */

2024-01-10 20:17 UTC, edsiper commented on plugins/out_azure_kusto/azure_kusto_ingest.c
> +                    //added kusto specific headers for debugging requests
please use /* */

2024-03-04 04:57 UTC, tanmaya-panda1 commented
@edsiper : request your review on this PR

2024-03-14 06:11 UTC, tanmaya-panda1 commented
Since these are kusto headers which are needed for tracking requests in kusto, we should not need any additional documentation update since it has no impact on the customer.

2024-07-04 18:47 UTC, closed without merging