in_splunk: out_splunk: Propagate ingested splunk_token authentication header
fluent/fluent-bit pull request #8738
Opened 2024-04-19 10:00 UTC by cosmo0920

Currently, in_splunk does not have a capability to store and propagate the ingested Splunk token.
This could be needed to handle for simplifying logs pipeline for ingesting payloads of Splunk HEC format.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [x] Example configuration file for the change

On terminal:

```console
$ bin/fluent-bit -i splunk -p port=8088 -o splunk -p port=8081 -psplunk_token=db496524-e7e6-4ae9-b3f0-2287d8e65cd4 -p "event_key=\$event" -f 1 -v
```

And another terminal:

```console
$ bin/fluent-bit -i splunk -p port=8081 -o stdout 
```

- [x] Debug log output from testing the change

```log
Fluent Bit v3.0.3
* Copyright (C) 2015-2024 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

___________.__                        __    __________.__  __          ________  
\_   _____/|  |  __ __   ____   _____/  |_  \______   \__|/  |_  ___  _\_____  \ 
 |    __)  |  | |  |  \_/ __ \ /    \   __\  |    |  _/  \   __\ \  \/ / _(__  < 
 |     \   |  |_|  |  /\  ___/|   |  \  |    |    |   \  ||  |    \   / /       \
 \___  /   |____/____/  \___  >___|  /__|    |______  /__||__|     \_/ /______  /
     \/                     \/     \/               \/                        \/ 

[2024/04/19 18:58:31] [ info] Configuration:
[2024/04/19 18:58:31] [ info]  flush time     | 1.000000 seconds
[2024/04/19 18:58:31] [ info]  grace          | 5 seconds
[2024/04/19 18:58:31] [ info]  daemon         | 0
[2024/04/19 18:58:31] [ info] ___________
[2024/04/19 18:58:31] [ info]  inputs:
[2024/04/19 18:58:31] [ info]      splunk
[2024/04/19 18:58:31] [ info] ___________
[2024/04/19 18:58:31] [ info]  filters:
[2024/04/19 18:58:31] [ info] ___________
[2024/04/19 18:58:31] [ info]  outputs:
[2024/04/19 18:58:31] [ info]      splunk.0
[2024/04/19 18:58:31] [ info] ___________
[2024/04/19 18:58:31] [ info]  collectors:
[2024/04/19 18:58:31] [ info] [fluent bit] version=3.0.3, commit=a01690abe6, pid=132087
[2024/04/19 18:58:31] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2024/04/19 18:58:31] [ info] [storage] ver=1.1.6, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2024/04/19 18:58:31] [ info] [cmetrics] version=0.8.0
[2024/04/19 18:58:31] [ info] [ctraces ] version=0.5.0
[2024/04/19 18:58:31] [ info] [input:splunk:splunk.0] initializing
[2024/04/19 18:58:31] [ info] [input:splunk:splunk.0] storage_strategy='memory' (memory only)
[2024/04/19 18:58:31] [debug] [splunk:splunk.0] created event channels: read=21 write=22
[2024/04/19 18:58:31] [debug] [downstream] listening on 0.0.0.0:8088
[2024/04/19 18:58:31] [debug] [splunk:splunk.0] created event channels: read=24 write=25
[2024/04/19 18:58:31] [ info] [sp] stream processor started
[2024/04/19 18:58:31] [ info] [output:splunk:splunk.0] worker #1 started
[2024/04/19 18:58:31] [ info] [output:splunk:splunk.0] worker #0 started
[2024/04/19 18:58:45] [debug] [task] created task=0x70ecd20365a0 id=0 OK
[2024/04/19 18:58:45] [debug] [output:splunk:splunk.0] task_id=0 assigned to thread #0
[2024/04/19 18:58:45] [debug] [upstream] KA connection #50 to 127.0.0.1:8081 is connected
[2024/04/19 18:58:45] [debug] [http_client] not using http_proxy for header
[2024/04/19 18:58:45] [debug] [upstream] KA connection #50 to 127.0.0.1:8081 is now available
[2024/04/19 18:58:45] [debug] [upstream] KA connection #50 to 127.0.0.1:8081 has been disconnected by the remote service
[2024/04/19 18:58:45] [debug] [out flush] cb_destroy coro_id=0
[2024/04/19 18:58:45] [debug] [task] destroy task=0x70ecd20365a0 (task_id=0)
[2024/04/19 18:58:46] [debug] [task] created task=0x70ecd20365a0 id=0 OK
[2024/04/19 18:58:46] [debug] [output:splunk:splunk.0] task_id=0 assigned to thread #1
[2024/04/19 18:58:46] [debug] [upstream] KA connection #49 to 127.0.0.1:8081 is connected
[2024/04/19 18:58:46] [debug] [http_client] not using http_proxy for header
[2024/04/19 18:58:46] [debug] [upstream] KA connection #49 to 127.0.0.1:8081 is now available
[2024/04/19 18:58:46] [debug] [upstream] KA connection #49 to 127.0.0.1:8081 has been disconnected by the remote service
[2024/04/19 18:58:46] [debug] [out flush] cb_destroy coro_id=0
[2024/04/19 18:58:46] [debug] [task] destroy task=0x70ecd20365a0 (task_id=0)
[2024/04/19 18:58:47] [debug] [task] created task=0x70ecd20365a0 id=0 OK
[2024/04/19 18:58:47] [debug] [output:splunk:splunk.0] task_id=0 assigned to thread #0
[2024/04/19 18:58:47] [debug] [upstream] KA connection #49 to 127.0.0.1:8081 is connected
[2024/04/19 18:58:47] [debug] [http_client] not using http_proxy for header
[2024/04/19 18:58:47] [debug] [upstream] KA connection #49 to 127.0.0.1:8081 is now available
[2024/04/19 18:58:47] [debug] [upstream] KA connection #49 to 127.0.0.1:8081 has been disconnected by the remote service
[2024/04/19 18:58:47] [debug] [out flush] cb_destroy coro_id=1
[2024/04/19 18:58:47] [debug] [task] destroy task=0x70ecd20365a0 (task_id=0)
^C[2024/04/19 18:58:51] [engine] caught signal (SIGINT)
[2024/04/19 18:58:51] [ warn] [engine] service will shutdown in max 5 seconds
[2024/04/19 18:58:51] [ info] [input] pausing splunk.0
[2024/04/19 18:58:52] [ info] [engine] service has stopped (0 pending tasks)
[2024/04/19 18:58:52] [ info] [input] pausing splunk.0
[2024/04/19 18:58:52] [ info] [output:splunk:splunk.0] thread worker #0 stopping...
[2024/04/19 18:58:52] [ info] [output:splunk:splunk.0] thread worker #0 stopped
[2024/04/19 18:58:52] [ info] [output:splunk:splunk.0] thread worker #1 stopping...
[2024/04/19 18:58:52] [ info] [output:splunk:splunk.0] thread worker #1 stopped
```

```log
Fluent Bit v3.0.3
* Copyright (C) 2015-2024 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

___________.__                        __    __________.__  __          ________  
\_   _____/|  |  __ __   ____   _____/  |_  \______   \__|/  |_  ___  _\_____  \ 
 |    __)  |  | |  |  \_/ __ \ /    \   __\  |    |  _/  \   __\ \  \/ / _(__  < 
 |     \   |  |_|  |  /\  ___/|   |  \  |    |    |   \  ||  |    \   / /       \
 \___  /   |____/____/  \___  >___|  /__|    |______  /__||__|     \_/ /______  /
     \/                     \/     \/               \/                        \/ 

[2024/04/19 18:58:35] [ info] Configuration:
[2024/04/19 18:58:35] [ info]  flush time     | 1.000000 seconds
[2024/04/19 18:58:35] [ info]  grace          | 5 seconds
[2024/04/19 18:58:35] [ info]  daemon         | 0
[2024/04/19 18:58:35] [ info] ___________
[2024/04/19 18:58:35] [ info]  inputs:
[2024/04/19 18:58:35] [ info]      splunk
[2024/04/19 18:58:35] [ info] ___________
[2024/04/19 18:58:35] [ info]  filters:
[2024/04/19 18:58:35] [ info] ___________
[2024/04/19 18:58:35] [ info]  outputs:
[2024/04/19 18:58:35] [ info]      stdout.0
[2024/04/19 18:58:35] [ info] ___________
[2024/04/19 18:58:35] [ info]  collectors:
[2024/04/19 18:58:35] [ info] [fluent bit] version=3.0.3, commit=a01690abe6, pid=132101
[2024/04/19 18:58:35] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2024/04/19 18:58:35] [ info] [storage] ver=1.1.6, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2024/04/19 18:58:35] [ info] [cmetrics] version=0.8.0
[2024/04/19 18:58:35] [ info] [ctraces ] version=0.5.0
[2024/04/19 18:58:35] [ info] [input:splunk:splunk.0] initializing
[2024/04/19 18:58:35] [ info] [input:splunk:splunk.0] storage_strategy='memory' (memory only)
[2024/04/19 18:58:35] [debug] [splunk:splunk.0] created event channels: read=21 write=22
[2024/04/19 18:58:35] [debug] [downstream] listening on 0.0.0.0:8081
[2024/04/19 18:58:35] [debug] [stdout:stdout.0] created event channels: read=24 write=25
[2024/04/19 18:58:35] [ info] [sp] stream processor started
[2024/04/19 18:58:35] [ info] [output:stdout:stdout.0] worker #0 started
[2024/04/19 18:58:46] [debug] [task] created task=0x70ef4 [...]

2024-04-19 15:28 UTC, edsiper requested changes

2024-04-19 15:28 UTC, edsiper commented on plugins/out_splunk/splunk.c
> +static flb_sds_t extract_hec_token(struct flb_splunk *ctx, msgpack_object *map)
please use a record accessor pattern instead

2024-04-22 05:06 UTC, cosmo0920 commented on plugins/out_splunk/splunk.c
> +static flb_sds_t extract_hec_token(struct flb_splunk *ctx, msgpack_object *map)
I used  record accessor pattern here: 
https://github.com/fluent/fluent-bit/pull/8738/commits/b134bf3bed4355e3880b6b52441e80aebe820ba3

2024-04-22 21:16 UTC, merged

2024-04-22 21:16 UTC, edsiper commented
thank you