out_cloudwatch_logs: Add support for log_group_class option
fluent/fluent-bit pull request #8826
Opened 2024-05-15 04:36 UTC by PettitWesley

New option in CloudWatch API.

This is rebased on top of the EKS Pod Identity feature support. 

## log_group_class user experience

### Warn Message that the log class is only set on create

```
[2024/05/15 04:08:58] [ warn] [output:cloudwatch_logs:cloudwatch_logs.2] Configured `log_group_class INFREQUENT_ACCESS` will only apply to log groups created by Fluent Bit. Look for the `Created log group` info level message emitted when a group does not already exist and is created.
```

### Suggested: Success message when logGroupClass is set successfull?

```
[2024/05/15 04:08:58] [ warn] [output:cloudwatch_logs:cloudwatch_logs.2] Configured `log_group_class INFREQUENT_ACCESS` for newly created log group flb-loggroupclass-test
```

### OperationAbortedException and retry when setting logGroupClass

This may happen for multiple reasons. In a cluster with many nodes, each FLB will try to create the log group on startup. This is why folks usually create the log group in CFN or somewhere else and not in FLB.

In my current test I only have one node so I am not sure why this happened

```
with error='OperationAbortedException', message='A conflicting operation is currently in progress against this resource. Please try again.'
[2024/05/15 04:15:34] [error] [output:cloudwatch_logs:cloudwatch_logs.0] Failed to create log group
[2024/05/15 04:15:34] [error] [output:cloudwatch_logs:cloudwatch_logs.0] Failed to send events
[2024/05/15 04:15:34] [ warn] [engine] failed to flush chunk '1-1715746529.827659013.flb', retry in 9 seconds: task_id=0, input=tail.0 > output=cloudwatch_logs.0 (out_id=0)
[2024/05/15 04:15:34] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Created log group infrequent-access-test/containerinsights/Bottlerocket-Linux-v1-29/application
```

```
[2024/05/15 04:15:34] [ info] [output:cloudwatch_logs:cloudwatch_logs.1] Creating log group infrequent-access-test/containerinsights/Bottlerocket-Linux-v1-29/dataplane
[2024/05/15 04:15:34] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Log Group infrequent-access-test/containerinsights/Bottlerocket-Linux-v1-29/application not found. Will attempt to create it.
[2024/05/15 04:15:34] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Creating log group infrequent-access-test/containerinsights/Bottlerocket-Linux-v1-29/application
[2024/05/15 04:15:34] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Log Group infrequent-access-test/containerinsights/Bottlerocket-Linux-v1-29/application not found. Will attempt to create it.
[2024/05/15 04:15:34] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Creating log group infrequent-access-test/containerinsights/Bottlerocket-Linux-v1-29/application
[2024/05/15 04:15:34] [error] [output:cloudwatch_logs:cloudwatch_logs.1] CreateLogGroup API responded with error='OperationAbortedException', message='A conflicting operation is currently in progress against this resource. Please try again.'
[2024/05/15 04:15:34] [error] [output:cloudwatch_logs:cloudwatch_logs.1] Failed to create log group
[2024/05/15 04:15:34] [error] [output:cloudwatch_logs:cloudwatch_logs.1] Failed to send events
[2024/05/15 04:15:34] [ warn] [engine] failed to flush chunk '1-1715746529.831506090.flb', retry in 8 seconds: task_id=3, input=systemd.3 > output=cloudwatch_logs.1 (out_id=1)
[2024/05/15 04:15:34] [ info] [output:cloudwatch_logs:cloudwatch_logs.1] Created log group infrequent-access-test/containerinsights/Bottlerocket-Linux-v1-29/dataplane
[2024/05/15 04:15:34] [ info] [output:cloudwatch_logs:cloudwatch_logs.1] Creating log stream ip-192-168-34-117.ca-central-1.compute.internal-dataplane.systemd.containerd.service in log group infrequent-access-test/containerinsights/Bottlerocket-Linux-v1-29/dataplane
[2024/05/15 04:15:34] [error] [output:cloudwatch_logs:cloudwatch_logs.0] CreateLogGroup API responded with error='OperationAbortedException', message='A conflicting operation is currently in progress against this resource. Please try again.'
[2024/05/15 04:15:34] [error] [output:cloudwatch_logs:cloudwatch_logs.0] Failed to create log group
[2024/05/15 04:15:34] [error] [output:cloudwatch_logs:cloudwatch_logs.0] Failed to send events
[2024/05/15 04:15:34] [ warn] [engine] failed to flush chunk '1-1715746529.827659013.flb', retry in 9 seconds: task_id=0, input=tail.0 > output=cloudwatch_logs.0 (out_id=0)
[2024/05/15 04:15:34] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Created log group infrequent-access-test/containerinsights/Bottlerocket-Linux-v1-29/application
[2024/05/15 04:15:34] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Creating log stream ip-192-168-34-117.ca-central-1.compute.internal-application.var.log.containers.fluent-bit-cff8cd566-gncts_amazon-cloudwatch_fluent-bit-7373602f7aaf4599d62c06bf4ac92d04a6dcc6f5e7f148a55cbb452f86b99b64.log in log group infrequent-access-test/containerinsights/Bottlerocket-Linux-v1-29/application
[2024/05/15 04:15:34] [ info] [output:cloudwatch_logs:cloudwatch_logs.1] Created log stream ip-192-168-34-117.ca-central-1.compute.internal-dataplane.systemd.containerd.service
[2024/05/15 04:15:34] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Created log stream ip-192-168-34-117.ca-central-1.compute.internal-application.var.log.containers.fluent-bit-cff8cd566-gncts_amazon-cloudwatch_fluent-bit-7373602f7aaf4599d62c06bf4ac92d04a6dcc6f5e7f148a55cbb452f86b99b64.log
[2024/05/15 04:15:42] [ info] [output:cloudwatch_logs:cloudwatch_logs.1] Creating log stream ip-192-168-34-117.ca-central-1.compute.internal-dataplane.systemd.kubelet.service in log group infrequent-access-test/containerinsights/Bottlerocket-Linux-v1-29/dataplane
[2024/05/15 04:15:42] [ info] [output:cloudwatch_logs:cloudwatch_logs.1] Created log stream ip-192-168-34-117.ca-central-1.compute.internal-dataplane.systemd.kubelet.service
[2024/05/15 04:15:42] [ info] [engine] flush chunk '1-1715746529.831506090.flb' succeeded at retry 1: task_id=3, input=systemd.3 > output=cloudwatch_logs.1 (out_id=1)
[2024/05/15 04:15:43] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Creating log stream ip-192-168-34-117.ca-central-1.compute.internal-application.var.log.containers.eks-pod-identity-agent-q5vxk_kube-system_eks-pod-identity-agent-59bc7f4cc8194e140161525d8c2db02008ca5718770d120cfe7d48f6a1203a21.log in log group infrequent-access-test/containerinsights/Bottlerocket-Linux-v1-29/application
[2024/05/15 04:15:43] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Created log stream ip-192-168-34-117.ca-central-1.compute.internal-application.var.log.containers.eks-pod-identity-agent-q5vxk_kube-system_eks-pod-identity-agent-59bc7f4cc8194e140161525d8c2db02008ca5718770d120cfe7d48f6a1203a21.log
[2024/05/15 04:15:43] [ info] [engine] flush chunk '1-1715746529.827659013.flb' succeeded at retry 1: task_id=0, input=tail.0 > output=cloudwatch_logs.0 (out_id=0)
```

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2024-05-15 14:31 UTC, edsiper requested changes
minor changes requested

2024-05-15 14:31 UTC, edsiper commented on src/flb_utils.c
> +char *flb_copy_host(const char *string, int pos_init, int pos_end)
if this interface will be from public use (nonstatic), the name must be prefixed according to the file, e.g: flb_utils_host_copy()

2024-05-15 14:31 UTC, edsiper commented on src/flb_utils.c
> +char *flb_copy_host_sds(const char *string, int pos_init, int pos_end)
if this interface will be from public use (non static), the name must be prefixed according the file, e.g: flb_utils_host_copy_sds()

2024-05-17 03:53 UTC, PettitWesley commented
```
147dda285fd4:bottlerocket-eks wppttt$ kubectl -n amazon-cloudwatch logs fluent-bit-fbf8584f8-vvsnl
Fluent Bit v1.9.10
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2024/05/17 03:47:44] [ info] [fluent bit] version=1.9.10, commit=7eb6b397eb, pid=1
[2024/05/17 03:47:44] [ info] [storage] version=1.4.0, type=memory+filesystem, sync=normal, checksum=disabled, max_chunks_up=128
[2024/05/17 03:47:44] [ info] [storage] backlog input plugin: storage_backlog.8
[2024/05/17 03:47:44] [ info] [cmetrics] version=0.3.7
[2024/05/17 03:47:44] [ info] [input:tail:tail.0] multiline core started
[2024/05/17 03:47:44] [ info] [input:tail:tail.1] multiline core started
[2024/05/17 03:47:44] [ info] [input:tail:tail.2] multiline core started
[2024/05/17 03:47:44] [ info] [input:systemd:systemd.3] seek_cursor=s=fd652eba798a44cc9ecbea19cdd2ac3e;i=1af... OK
[2024/05/17 03:47:44] [ info] [input:tail:tail.4] multiline core started
[2024/05/17 03:47:44] [ info] [input:storage_backlog:storage_backlog.8] queue memory limit: 4.8M
[2024/05/17 03:47:44] [ info] [filter:kubernetes:kubernetes.0] https=1 host=127.0.0.1 port=10250
[2024/05/17 03:47:44] [ info] [filter:kubernetes:kubernetes.0]  token updated
[2024/05/17 03:47:44] [ info] [filter:kubernetes:kubernetes.0] local POD info OK
[2024/05/17 03:47:44] [ info] [filter:kubernetes:kubernetes.0] testing connectivity with Kubelet...
[2024/05/17 03:47:44] [ info] [filter:kubernetes:kubernetes.0] connectivity OK
[2024/05/17 03:47:44] [ warn] [output:cloudwatch_logs:cloudwatch_logs.0] Configured `log_group_class INFREQUENT_ACCESS` will only apply to log groups created by Fluent Bit. Look for the `Created log group` info level message emitted when a group does not already exist and is created.
[2024/05/17 03:47:44] [ warn] [output:cloudwatch_logs:cloudwatch_logs.1] Configured `log_group_class INFREQUENT_ACCESS` will only apply to log groups created by Fluent Bit. Look for the `Created log group` info level message emitted when a group does not already exist and is created.
[2024/05/17 03:47:44] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] worker #0 started
[2024/05/17 03:47:44] [ info] [output:cloudwatch_logs:cloudwatch_logs.1] worker #0 started
[2024/05/17 03:47:44] [ info] [output:cloudwatch_logs:cloudwatch_logs.2] worker #0 started
[2024/05/17 03:47:44] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
[2024/05/17 03:47:44] [ info] [sp] stream processor started
[2024/05/17 03:47:44] [ info] [input:tail:tail.0] inotify_fs_add(): inode=42307 watch_fd=1 name=/var/log/containers/coredns-68c6b7b454-r6t8q_kube-system_coredns-1709ec5295314385997364635ee603e6d6a559f6cfb70bf3f3e2c431355833c5.log
[2024/05/17 03:47:44] [ info] [input:tail:tail.0] inotify_fs_add(): inode=167812073 watch_fd=2 name=/var/log/containers/coredns-68c6b7b454-tc5mh_kube-system_coredns-2cd2d04c3f2bc1460ac0e86dbd1c3b3b3f8ba0828fc97cc122b491ce897b457e.log
[2024/05/17 03:47:44] [ info] [input:tail:tail.0] inotify_fs_add(): inode=201708930 watch_fd=3 name=/var/log/containers/eks-pod-identity-agent-q5vxk_kube-system_eks-pod-identity-agent-init-809c5a47b01cca41b44dc18b54b81ab3f3753d1caae2c0c0ca1f6439b5fa4ae3.log
[2024/05/17 03:47:44] [ info] [input:tail:tail.4] inotify_fs_add(): inode=218165991 watch_fd=1 name=/var/log/containers/aws-node-jhslt_kube-system_aws-eks-nodeagent-f083e3e56bc143254ca23011138731a632725afa821c9fc1f442f4e0901eef29.log
[2024/05/17 03:47:44] [ info] [input:tail:tail.4] inotify_fs_add(): inode=16777403 watch_fd=2 name=/var/log/containers/aws-node-jhslt_kube-system_aws-node-7cd53aacd33b6193b69e8085093fe6876e3d0dcda16f4003813528a7c378059e.log
[2024/05/17 03:47:44] [ info] [input:tail:tail.4] inotify_fs_add(): inode=117531748 watch_fd=3 name=/var/log/containers/aws-node-jhslt_kube-system_aws-vpc-cni-init-e5fe7f223d165f4b1c55d1bcc3b8e9f47aa1a475f45d8b3e83c2a1070e82f941.log
[2024/05/17 03:47:44] [ info] [input:tail:tail.0] inotify_fs_add(): inode=185075710 watch_fd=4 name=/var/log/containers/eks-pod-identity-agent-q5vxk_kube-system_eks-pod-identity-agent-59bc7f4cc8194e140161525d8c2db02008ca5718770d120cfe7d48f6a1203a21.log
[2024/05/17 03:47:44] [ info] [input:tail:tail.1] inotify_fs_add(): inode=218429523 watch_fd=1 name=/var/log/containers/fluent-bit-fbf8584f8-vvsnl_amazon-cloudwatch_fluent-bit-1deecf439298817933984983865ffed777bf4347c4b8d42a1562f215cc12468a.log
[2024/05/17 03:47:44] [ info] [input:tail:tail.4] inotify_fs_add(): inode=100789792 watch_fd=4 name=/var/log/containers/kube-proxy-pgx7n_kube-system_kube-proxy-5a8416e3845cdf77cbdc4789db4e1494b6959b912afb07c6d39158e1d41dbc61.log
[2024/05/17 03:47:49] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Creating log stream ip-192-168-34-117.ca-central-1.compute.internal-application.var.log.containers.eks-pod-identity-agent-q5vxk_kube-system_eks-pod-identity-agent-59bc7f4cc8194e140161525d8c2db02008ca5718770d120cfe7d48f6a1203a21.log in log group infrequent-access-test16/containerinsights/Bottlerocket-Linux-v1-29/application
[2024/05/17 03:47:49] [ info] [output:cloudwatch_logs:cloudwatch_logs.1] Creating log stream ip-192-168-34-117.ca-central-1.compute.internal-dataplane.systemd.containerd.service in log group infrequent-access-test16/containerinsights/Bottlerocket-Linux-v1-29/dataplane
[2024/05/17 03:47:49] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Creating log stream ip-192-168-34-117.ca-central-1.compute.internal-application.var.log.containers.fluent-bit-fbf8584f8-vvsnl_amazon-cloudwatch_fluent-bit-1deecf439298817933984983865ffed777bf4347c4b8d42a1562f215cc12468a.log in log group infrequent-access-test16/containerinsights/Bottlerocket-Linux-v1-29/application
[2024/05/17 03:47:49] [ info] [output:cloudwatch_logs:cloudwatch_logs.1] Creating log stream ip-192-168-34-117.ca-central-1.compute.internal-dataplane.systemd.kubelet.service in log group infrequent-access-test16/containerinsights/Bottlerocket-Linux-v1-29/dataplane
[2024/05/17 03:47:49] [ info] [output:cloudwatch_logs:cloudwatch_logs.1] Creating log stream ip-192-168-34-117.ca-central-1.compute.internal-dataplane.tail.var.log.containers.kube-proxy-pgx7n_kube-system_kube-proxy-5a8416e3845cdf77cbdc4789db4e1494b6959b912afb07c6d39158e1d41dbc61.log in log group infrequent-access-test16/containerinsights/Bottlerocket-Linux-v1-29/dataplane
[2024/05/17 03:47:49] [ info] [output:cloudwatch_logs:cloudwatch_logs.1] Log Group infrequent-access-test16/containerinsights/Bottlerocket-Linux-v1-29/dataplane not found. Will attempt to create it.
[2024/05/17 03:47:49] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Log Group infrequent-access-test16/containerinsights/Bottlerocket-Linux-v1-29/application not found. Will attempt to create it.
[2024/05/17 03:47:49] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Creating log group infrequent-access-test16/containerinsights/Bottlerocket-Linux-v1-29/application
[2024/05/17 03:47:49] [ info] [output:cloudwatch_logs:cloudwatch_logs.1] Creating log group infrequent-access-test16/containerinsights/Bottlerocket-Linux-v1-29/dataplane
[2024/05/17 03:47:49] [ info] [output:cloudwatch_logs:cloudwatch_logs.1] Log Group infrequent-access-test16/containerinsights/Bottlerocket-Linux-v1-29/dataplane not found. Will attempt to create it.
[2024/05/17 03:47:49] [ info] [output:cloudwatch_logs:cloudwatch_logs.1] Creating log group infrequent-access-test16/containerinsights/Bottlerocket-Linux-v1-29/dataplane
[2024/05/17 03:47:49] [ info] [output:cloudwatch_logs:cloudwatch_logs.1] Log Group infrequent-access-test16/containerinsights/Bottlerocket-Linux-v1-29/dataplane not found. Will attempt to create it.
[2024/05/17 03:47:49] [ info] [output:cloudwatch_logs:cloudwatch_logs.1] Creating log group infrequent-access-test16/containerinsights/Bottlerocket-Linux-v1-29/dataplane
[2024/05/17 03:47:49] [ info] [output:cloudwatch_logs:cloudwatch_logs.0] Log Group infrequent-access-test16/containerinsights/Bottlerocket-Linux-v1-29/ap [...]

2024-05-17 04:30 UTC, PettitWesley commented
Closing in favor of: https://github.com/fluent/fluent-bit/pull/8832

2024-05-17 04:30 UTC, closed without merging