in_splunk: Add switch for storing in metadata or records and handle multiple tokens on in splunk
fluent/fluent-bit pull request #8900
Opened 2024-05-31 03:08 UTC by cosmo0920

In this enhancement, I implemented capabilities for storing metadata into records and handle multiple HEC tokens in configuration.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [x] Example configuration file for the change

### For injecting HEC tokens into records case

```ini
[INPUT]
    Name splunk
    Tag splunk.test.ingest
    HTTP2 off
    store_token_to_metadata off
    Splunk_Token 7bba8847-4aee-4e62-ba7b-08c6139e42b9,4e63c0c9-c3b5-4a0a-bf4d-bfd5bc0d0070
[OUTPUT]
    Name stdout
    Match *
```

### For injecting HEC tokens into metadata case (default behavior)

```ini
[INPUT]
    Name splunk
    Tag splunk.test.ingest
    HTTP2 off
    store_token_to_metadata on
    Splunk_Token 7bba8847-4aee-4e62-ba7b-08c6139e42b9,4e63c0c9-c3b5-4a0a-bf4d-bfd5bc0d0070
[OUTPUT]
    Name stdout
    Match *
```

- [x] Debug log output from testing the change

### For injecting HEC tokens into records case

```log
Fluent Bit v3.0.7
* Copyright (C) 2015-2024 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

___________.__                        __    __________.__  __          ________
\_   _____/|  |  __ __   ____   _____/  |_  \______   \__|/  |_  ___  _\_____  \
 |    __)  |  | |  |  \_/ __ \ /    \   __\  |    |  _/  \   __\ \  \/ / _(__  <
 |     \   |  |_|  |  /\  ___/|   |  \  |    |    |   \  ||  |    \   / /       \
 \___  /   |____/____/  \___  >___|  /__|    |______  /__||__|     \_/ /______  /
     \/                     \/     \/               \/                        \/

[2024/05/31 12:03:27] [ info] Configuration:
[2024/05/31 12:03:27] [ info]  flush time     | 1.000000 seconds
[2024/05/31 12:03:27] [ info]  grace          | 5 seconds
[2024/05/31 12:03:27] [ info]  daemon         | 0
[2024/05/31 12:03:27] [ info] ___________
[2024/05/31 12:03:27] [ info]  inputs:
[2024/05/31 12:03:27] [ info]      splunk
[2024/05/31 12:03:27] [ info] ___________
[2024/05/31 12:03:27] [ info]  filters:
[2024/05/31 12:03:27] [ info] ___________
[2024/05/31 12:03:27] [ info]  outputs:
[2024/05/31 12:03:27] [ info]      stdout.0
[2024/05/31 12:03:27] [ info] ___________
[2024/05/31 12:03:27] [ info]  collectors:
[2024/05/31 12:03:27] [ info] [fluent bit] version=3.0.7, commit=c08585c3e4, pid=18705
[2024/05/31 12:03:27] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2024/05/31 12:03:27] [ info] [output:stdout:stdout.0] worker #0 started
[2024/05/31 12:03:27] [ info] [storage] ver=1.5.2, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2024/05/31 12:03:27] [ info] [cmetrics] version=0.9.0
[2024/05/31 12:03:27] [ info] [ctraces ] version=0.5.1
[2024/05/31 12:03:27] [ info] [input:splunk:splunk.0] initializing
[2024/05/31 12:03:27] [ info] [input:splunk:splunk.0] storage_strategy='memory' (memory only)
[2024/05/31 12:03:27] [debug] [splunk:splunk.0] created event channels: read=21 write=22
[2024/05/31 12:03:27] [debug] [downstream] listening on 0.0.0.0:8088
[2024/05/31 12:03:27] [debug] [stdout:stdout.0] created event channels: read=24 write=25
[2024/05/31 12:03:27] [ info] [sp] stream processor started
[2024/05/31 12:03:28] [debug] [input:splunk:splunk.0] Mark as unknown type for ingested payloads
[2024/05/31 12:03:29] [debug] [task] created task=0x5f57900 id=0 OK
[2024/05/31 12:03:29] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
==18705== Warning: client switching stacks?  SP change: 0x79ec358 --> 0x5f63ec0
==18705==          to suppress, use: --max-stackframe=27821208 or greater
==18705== Warning: client switching stacks?  SP change: 0x5f63da8 --> 0x79ec358
==18705==          to suppress, use: --max-stackframe=27821488 or greater
==18705== Warning: client switching stacks?  SP change: 0x79ec358 --> 0x5f63da8
==18705==          to suppress, use: --max-stackframe=27821488 or greater
==18705==          further instances of this message will not be shown.
[0] splunk.test.ingest: [[1717124609.001690922, {}], {"event"=>"hello world", "@splunk_token"=>"Splunk 7bba8847-4aee-4e62-ba7b-08c6139e42b9"}]
[2024/05/31 12:03:29] [debug] [out flush] cb_destroy coro_id=0
[2024/05/31 12:03:29] [debug] [task] destroy task=0x5f57900 (task_id=0)
[2024/05/31 12:03:36] [debug] [input:splunk:splunk.0] Mark as unknown type for ingested payloads
[2024/05/31 12:03:37] [debug] [task] created task=0x6061290 id=0 OK
[2024/05/31 12:03:37] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] splunk.test.ingest: [[1717124616.904557127, {}], {"event"=>"hello world", "@splunk_token"=>"Splunk 4e63c0c9-c3b5-4a0a-bf4d-bfd5bc0d0070"}]
[2024/05/31 12:03:37] [debug] [out flush] cb_destroy coro_id=1
[2024/05/31 12:03:37] [debug] [task] destroy task=0x6061290 (task_id=0)
^C[2024/05/31 12:04:40] [engine] caught signal (SIGINT)
[2024/05/31 12:04:40] [ warn] [engine] service will shutdown in max 5 seconds
[2024/05/31 12:04:40] [ info] [input] pausing splunk.0
[2024/05/31 12:04:40] [ info] [engine] service has stopped (0 pending tasks)
[2024/05/31 12:04:40] [ info] [input] pausing splunk.0
[2024/05/31 12:04:40] [ info] [output:stdout:stdout.0] thread worker #0 stopping...
[2024/05/31 12:04:40] [ info] [output:stdout:stdout.0] thread worker #0 stopped
```

### For injecting HEC tokens into metadata case (default behavior)

```log
Fluent Bit v3.0.7
* Copyright (C) 2015-2024 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

___________.__                        __    __________.__  __          ________
\_   _____/|  |  __ __   ____   _____/  |_  \______   \__|/  |_  ___  _\_____  \
 |    __)  |  | |  |  \_/ __ \ /    \   __\  |    |  _/  \   __\ \  \/ / _(__  <
 |     \   |  |_|  |  /\  ___/|   |  \  |    |    |   \  ||  |    \   / /       \
 \___  /   |____/____/  \___  >___|  /__|    |______  /__||__|     \_/ /______  /
     \/                     \/     \/               \/                        \/

[2024/05/31 12:06:07] [ info] Configuration:
[2024/05/31 12:06:07] [ info]  flush time     | 1.000000 seconds
[2024/05/31 12:06:07] [ info]  grace          | 5 seconds
[2024/05/31 12:06:07] [ info]  daemon         | 0
[2024/05/31 12:06:07] [ info] ___________
[2024/05/31 12:06:07] [ info]  inputs:
[2024/05/31 12:06:07] [ info]      splunk
[2024/05/31 12:06:07] [ info] ___________
[2024/05/31 12:06:07] [ info]  filters:
[2024/05/31 12:06:07] [ info] ___________
[2024/05/31 12:06:07] [ info]  outputs:
[2024/05/31 12:06:07] [ info]      stdout.0
[2024/05/31 12:06:07] [ info] ___________
[2024/05/31 12:06:07] [ info]  collectors:
[2024/05/31 12:06:07] [ info] [fluent bit] version=3.0.7, commit=c08585c3e4, pid=19348
[2024/05/31 12:06:07] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2024/05/31 12:06:07] [ info] [output:stdout:stdout.0] worker #0 started
[2024/05/31 12:06:07] [ info] [storage] ver=1.5.2, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2024/05/31 12:06:07] [ info] [cmetrics] version=0.9.0
[2024/05/31 12:06:07] [ info] [ctraces ] version=0.5.1
[2024/05/31 12:06:07] [ info] [input:splunk:splunk.0] initializing
[2024/05/31 12:06:07] [ info] [input:splunk:splunk.0] storage_strategy='memory' (memory only)
[2024/05/31 12:06:07] [debug] [splunk:splunk.0] created event channels: read=21 write=22
[2024/05/31 12:06:07] [debug] [downstream] listening on 0.0.0.0:8088
[2024/05/31 12:06:07] [debug] [stdout:stdout.0] created event channels: read=24 write=25
[2024/05/31 12:06:07] [ info] [sp] stream processor started
[2024/05/31 12:06:09] [debug] [input:splunk:splunk.0] Mark as unknown type for ingested payloads
[2024/05/31 12:06:09] [debug] [task] created task=0x5f5d9c0 id=0 OK
[2024/05/31 12:06:09] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
==19348== Warning: client switching stacks?  SP change: 0x79ec358 --> 0x5f63ec0
==19348==          to suppress, use: --max-stackframe=278 [...]

2024-05-31 03:09 UTC, cosmo0920 commented
Note that this PR is built on top of https://github.com/fluent/fluent-bit/pull/8883 commit. Because raw endpoint unit testing should fail without that PR's change,

2024-06-02 20:44 UTC, edsiper commented
FYI: #8883 has been merged.

2024-06-03 21:21 UTC, edsiper requested changes

2024-06-03 21:21 UTC, edsiper commented on plugins/in_splunk/splunk_config.c
> +            token = strtok(NULL, ",");
we avoid using strtok(2) function since it modifies the original buffer.

2024-06-03 21:21 UTC, edsiper commented on plugins/in_splunk/splunk.c
> +     FLB_CONFIG_MAP_BOOL, "store_token_to_metadata", "true",
I would suggest a little change to `store_token_in_metadata"

2024-06-03 21:21 UTC, edsiper commented on plugins/in_splunk/splunk_config.c
> +        token = strtok(tmp_tokens, ",");
avoid strtok(). you can use flb_utls_split instead

2024-06-03 21:21 UTC, edsiper commented on plugins/in_splunk/splunk_config.c
> +        tmp_tokens = flb_strdup(tmp);
validate the return value

2024-06-03 21:21 UTC, edsiper commented on plugins/in_splunk/splunk_prot.c
> +        mk_list_foreach_safe(head, tmp, &ctx->auth_tokens) {
if the list entry won't be deleted, you can use `mk_list_foreach()` , the `_safe_` version aims to provide an extra pointer to deal with cases where entries/nodes are being removed.

2024-06-05 17:50 UTC, edsiper approved these changes

2024-06-05 17:50 UTC, merged