Add Port config option for Kinesis plugin
fluent/fluent-bit pull request #9171
Opened 2024-08-06 17:52 UTC by Athishpranav2003

Add option to configure port for Kinesis plugin

#9160 
----

**Testing**
Before we can approve your change; please submit the following in a comment:

- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [x] Documentation required for this feature

Will make the doc PR soon
**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2024-08-07 05:26 UTC, Athishpranav2003 commented
@PettitWesley Can you please check this PR

2024-08-07 07:42 UTC, Athishpranav2003 commented
@cosmo0920 seems like @PettitWesley is inactive for a while. Is it possible if this PR can be reassigned?

2024-08-09 07:06 UTC, Athishpranav2003 commented
@ashie seems like no one is responding to this PR. Could you please help me get this checked with the right person :)

2024-08-09 10:50 UTC, cosmo0920 commented
Could you add a documentation PR for corresponding this?
Documentation repo is here: https://github.com/fluent/fluent-bit-docs

2024-08-09 11:33 UTC, Athishpranav2003 commented
@cosmo0920 it's already done and got approved https://github.com/fluent/fluent-bit-docs/pull/1421

I didn't know he is not part of Fluent-bit :(

2024-08-12 09:33 UTC, Athishpranav2003 commented
@cosmo0920 any updates on this?

2024-08-20 01:53 UTC, Athishpranav2003 commented
@cosmo0920 ping for review

2024-08-21 03:05 UTC, Athishpranav2003 commented
@edsiper ping for review

2024-08-30 06:18 UTC, cosmo0920 commented on plugins/out_kinesis_streams/kinesis.c
> +     0, FLB_FALSE, 0,
If there is a default value here, you should specify set_property part as `FLB_TRUE`.

See: https://github.com/fluent/fluent-bit/blob/master/include/fluent-bit/flb_config_map.h#L75

2024-09-02 06:23 UTC, cosmo0920 requested changes
Adding test cases and port number assertions would be good to have.

2024-09-02 08:45 UTC, Athishpranav2003 commented
@cosmo0920 i guess we cant access the member variables here so asserting port number seems not possible. Is there any wrapper that exposes these internal struct variables? I couldnt see similar tests in other runtime tests

2024-09-02 10:44 UTC, cosmo0920 commented
> [Athishpranav2003](https://github.com/Athishpranav2003) commented [2 hours ago](https://github.com/fluent/fluent-bit/pull/9171#issuecomment-2324166998) • 
@cosmo0920 i guess we cant access the member variables here so asserting port number seems not possible. Is there any wrapper that exposes these internal struct variables? I couldnt see similar tests in other runtime tests

For now i have added the port configuration too in the UT

We can use flb_lib mechanism for testing with configs. 
Unfortunately, #9317 would be good because this PR has associated unit tests and port range assertion. So, I’ll close this PR.

2024-09-02 10:54 UTC, closed without merging