tls: improve cert load and error logging for handshake.
fluent/fluent-bit pull request #9527
Opened 2024-10-25 10:59 UTC by niedbalski

**Description**

While working on troubleshoot the TLS certificate load failures, I noticed some of important issues
that affected my capacity to further diagnose the underlying TLS issues with the users.

1.  Users with expired CA never got to understand the root cause by reading the log message, although this information is available on the x509 error details. (https://x509errors.org/) 
```
[2024/09/16 10:00:38] [error] [tls] error: unexpected EOF with reason: certificate verify failed
```
2. Loading and reading issues from the windows certificate store where masqueraded into a single error, the error can be in the enlisting, load (enumerating/existing) or in other parts of the code, but those are just returned as a single error.

This patch adds extra trace/debug information to the openssl certificate load process (parsing and adding)
to help the user to identify the cause of any failure during initialisation. 

The intention is to improve the information around CA certs missing, inaccessible, handshake errors
with extra details (such as  X509 verification issues) for easier troubleshooting. I have also taken some time on improved the code readability and logs around the SSL handshake handling. 

**Testing**

Configuration I have used.

```ini
[SERVICE]
    log_level debug

[CUSTOM]
    name calyptia
    api_key xxx
    fleet_name test-jorge
    calyptia_tls.verify on
    calyptia_host cloud-api-staging.calyptia.com
```

**Documentation**

N/A

**Backporting**

- [X] Backport to latest stable release.
----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2024-10-25 20:40 UTC, edsiper requested changes

2024-10-25 20:40 UTC, edsiper commented on src/tls/openssl.c
> +    // Check if OpenSSL certificate store is available
https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#single-line-comment

2024-10-25 20:40 UTC, edsiper commented on src/tls/openssl.c
> +    // Open the Windows system certificate store
https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#single-line-comment

2024-10-25 20:40 UTC, edsiper commented on src/tls/openssl.c
> +    // Clear any previous SSL errors
https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#single-line-comment

2024-10-28 06:34 UTC, cosmo0920 requested changes
I found other code style issues. Basically, the added diffs are properly handled for errors. But, we need to `/* ... */` style of one line comments.

2024-10-28 06:34 UTC, cosmo0920 commented on src/tls/openssl.c
> +    if (ret == 1) {
:+1:
I just confused the condition but it is correct. `SSL_accept` returns 1 when connection is established.
https://docs.openssl.org/master/man3/SSL_accept/#return-values

2024-10-28 06:34 UTC, cosmo0920 commented on src/tls/openssl.c
> +                    const char *x509_err = X509_verify_cert_error_string(ssl_code);
Probably, we encourage to define this variable on the top part of this function.
https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#variable-definitions

2024-10-28 06:34 UTC, cosmo0920 commented on src/tls/openssl.c
> +                unsigned long err = ERR_get_error();
Ditto.
https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#variable-definitions

2024-10-28 18:04 UTC, niedbalski commented
@edsiper @cosmo0920 fixed the issues.

2024-10-29 06:50 UTC, cosmo0920 approved these changes

2024-10-29 08:26 UTC, merged