loki_out: add stuctured_metadata_map_keys
fluent/fluent-bit pull request #9530
Opened 2024-10-25 15:14 UTC by 0x006EA1E5

* Adds stuctured_metadata_map_keys config to dynamically populate stuctured_metadata from a map

Addresses #9463 
----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2024-11-28 17:21 UTC, 0x006EA1E5 commented on plugins/out_loki/loki.c
> +                         * Does this need optimising? For example, to handle
Can anyone answer this question? Should I optimise this somehow?

2024-11-28 17:22 UTC, 0x006EA1E5 commented on plugins/out_loki/loki.h
> +    struct mk_list *structured_metadata_map_keys;
is this config property name okay `structured_metadata_map_keys`?

2024-11-28 17:25 UTC, 0x006EA1E5 commented on tests/runtime/out_loki.c
> +void flb_test_structured_metadata_map_params(char *remove_keys,
There are quite a few different variations on this test, so I have created this function which takes various parameters, and then called it for each actual test (below)

2024-11-28 17:25 UTC, 0x006EA1E5 commented on tests/runtime/out_loki.c
> +        flb_test_structured_metadata_map_single_missing_map},
Any test cases missing that I should add?

2024-11-28 17:29 UTC, 0x006EA1E5 commented on plugins/out_loki/loki.c
> +     * explicit structured_metadata entries override
I believe this works as expected. 

The intention is, if we try to add an entry to the structured_metadata with the same key twice (first from the new `structured_metadata_map_keys`, then from the existing `structured_metadata`), then the second entry should "win" and overrwite the first.

I am assuming msgpack works this way. But maybe I actually need to do some kind of explicit check, and only add a new entry where there is not already one for a given key?

2024-11-28 17:33 UTC, 0x006EA1E5 commented on plugins/out_loki/loki.c
> +static void pack_maps(struct flb_loki *ctx,
This essentially tries to follow the flow of the proceeding `pack_kv` function.

Do you need a more detailed spec of what exactly this is supposed to be doing?

It should implement the proposal descibed in the FR https://github.com/fluent/fluent-bit/issues/9463

2024-12-10 16:14 UTC, 0x006EA1E5 commented
I added a PR for the docs here https://github.com/fluent/fluent-bit-docs/pull/1527

2025-01-14 16:49 UTC, 0x006EA1E5 commented
Example config file, for sending logs to Loki at Grafana Cloud:
```service:
  log_level: info

pipeline:
  inputs:
    - name: dummy
      tag: logs
      dummy: '{"message":"simple log generated","logger":"com.example.me.MyClass","level":"INFO","hostname":"OM-M07GV2J252","structured_metadata_attributes":{"a":"hello","b":"world!"}}'

  outputs:
    - name: loki
      match: logs
      host: ${LOKI_HOST}
      http_passwd: ${GRAFANA_TOKEN}
      http_user: ${LOKI_USER_ID}
      remove_keys: hostname
      label_keys: $level,$logger
      labels: service_name=test
      structured_metadata: $hostname
      structured_metadata_map_keys: $structured_metadata_attributes
      line_format: key_value
      drop_single_key: on
      compress: gzip
      port: 443
      tls: true
      tls.verify: true
```

2025-01-14 17:42 UTC, 0x006EA1E5 commented
valgrind output for `flb-rt-out_loki` unit test 
```
==131535== Memcheck, a memory error detector
==131535== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==131535== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==131535== Command: /IdeaProjects/fluent-bit/cmake-build-debug/bin/flb-rt-out_loki
==131535== 
Test remove_keys_remove_map...                  [ OK ]
Test labels_ra...                               [ OK ]
Test remove_keys...                             [ OK ]
Test basic...                                   [ OK ]
Test labels...                                  [ OK ]
Test label_keys...                              [ OK ]
Test line_format...                             [ OK ]
Test drop_single_key_off...                     [ OK ]
Test drop_single_key_on...                      [ OK ]
Test drop_single_key_raw...                     [ OK ]
Test label_map_path...                          [ OK ]
Test float_value...                             [ OK ]
Test structured_metadata_map_single_map...      [ OK ]
Test structured_metadata_map_two_maps...        [ OK ]
Test structured_metadata_map_sub_map...         [ OK ]
Test structured_metadata_map_both_with_non_map_value... [ OK ]
Test structured_metadata_map_value_explicit_override_map_key... [ OK ]
Test structured_metadata_explicit_only_no_map... [ OK ]
Test structured_metadata_explicit_only_map...   [ OK ]
Test structured_metadata_map_and_explicit...    [ OK ]
Test structured_metadata_map_single_missing_map... [ OK ]
SUCCESS: All unit tests have passed.
==131535== 
==131535== HEAP SUMMARY:
==131535==     in use at exit: 0 bytes in 0 blocks
==131535==   total heap usage: 34,441 allocs, 34,441 frees, 16,366,899 bytes allocated
==131535== 
==131535== All heap blocks were freed -- no leaks are possible
==131535== 
==131535== For lists of detected and suppressed errors, rerun with: -s
==131535== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

2025-01-14 17:46 UTC, 0x006EA1E5 commented
valgrind output from test config (confirmed sending logs correctly downstream)
```
==132953== Memcheck, a memory error detector
==132953== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==132953== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==132953== Command: /IdeaProjects/fluent-bit/cmake-build-debug/bin/fluent-bit -c ./fluent-bit_loki_out-structured_metadata_map.yaml
==132953== 
Fluent Bit v4.0.0
* Copyright (C) 2015-2024 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

______ _                  _    ______ _ _             ___  _____ 
|  ___| |                | |   | ___ (_) |           /   ||  _  |
| |_  | |_   _  ___ _ __ | |_  | |_/ /_| |_  __   __/ /| || |/' |
|  _| | | | | |/ _ \ '_ \| __| | ___ \ | __| \ \ / / /_| ||  /| |
| |   | | |_| |  __/ | | | |_  | |_/ / | |_   \ V /\___  |\ |_/ /
\_|   |_|\__,_|\___|_| |_|\__| \____/|_|\__|   \_/     |_(_)___/ 


[2025/01/14 17:45:04] [ info] Configuration:
[2025/01/14 17:45:04] [ info]  flush time     | 1.000000 seconds
[2025/01/14 17:45:04] [ info]  grace          | 5 seconds
[2025/01/14 17:45:04] [ info]  daemon         | 0
[2025/01/14 17:45:04] [ info] ___________
[2025/01/14 17:45:04] [ info]  inputs:
[2025/01/14 17:45:04] [ info]      dummy
[2025/01/14 17:45:04] [ info] ___________
[2025/01/14 17:45:04] [ info]  filters:
[2025/01/14 17:45:04] [ info] ___________
[2025/01/14 17:45:04] [ info]  outputs:
[2025/01/14 17:45:04] [ info]      loki.0
[2025/01/14 17:45:04] [ info] ___________
[2025/01/14 17:45:04] [ info]  collectors:
[2025/01/14 17:45:04] [ info] [fluent bit] version=4.0.0, commit=4f158a5d1c, pid=132953
[2025/01/14 17:45:04] [debug] [engine] coroutine stack size: 196608 bytes (192.0K)
[2025/01/14 17:45:04] [ info] [storage] ver=1.5.2, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2025/01/14 17:45:04] [ info] [simd    ] disabled
[2025/01/14 17:45:04] [ info] [cmetrics] version=0.9.9
[2025/01/14 17:45:04] [ info] [ctraces ] version=0.5.7
[2025/01/14 17:45:04] [ info] [input:dummy:dummy.0] initializing
[2025/01/14 17:45:04] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2025/01/14 17:45:04] [debug] [dummy:dummy.0] created event channels: read=25 write=26
[2025/01/14 17:45:04] [debug] [loki:loki.0] created event channels: read=27 write=28
[2025/01/14 17:45:04] [debug] [output:loki:loki.0] remove_mpa size: 4
[2025/01/14 17:45:04] [ info] [output:loki:loki.0] configured, hostname=logs-prod-006.grafana.net:443
[2025/01/14 17:45:04] [ info] [sp] stream processor started
[2025/01/14 17:45:06] [debug] [task] created task=0x5735150 id=0 OK
[2025/01/14 17:45:07] [debug] [upstream] KA connection #35 to logs-prod-006.grafana.net:443 is connected
[2025/01/14 17:45:07] [debug] [http_client] not using http_proxy for header
[2025/01/14 17:45:07] [debug] [task] created task=0x58dd770 id=1 OK
[2025/01/14 17:45:07] [debug] [output:loki:loki.0] logs-prod-006.grafana.net:443, HTTP status=204
[2025/01/14 17:45:07] [debug] [upstream] KA connection #35 to logs-prod-006.grafana.net:443 is now available
[2025/01/14 17:45:07] [debug] [out flush] cb_destroy coro_id=0
[2025/01/14 17:45:07] [debug] [task] destroy task=0x5735150 (task_id=0)
[2025/01/14 17:45:07] [debug] [upstream] KA connection #36 to logs-prod-006.grafana.net:443 is connected
[2025/01/14 17:45:07] [debug] [http_client] not using http_proxy for header
[2025/01/14 17:45:08] [debug] [output:loki:loki.0] logs-prod-006.grafana.net:443, HTTP status=204
[2025/01/14 17:45:08] [debug] [upstream] KA connection #36 to logs-prod-006.grafana.net:443 is now available
[2025/01/14 17:45:08] [debug] [out flush] cb_destroy coro_id=1
[2025/01/14 17:45:08] [debug] [task] destroy task=0x58dd770 (task_id=1)
[2025/01/14 17:45:08] [debug] [task] created task=0x6a7b960 id=0 OK
[2025/01/14 17:45:08] [debug] [upstream] KA connection #35 to logs-prod-006.grafana.net:443 has been assigned (recycled)
[2025/01/14 17:45:08] [debug] [http_client] not using http_proxy for header
[2025/01/14 17:45:08] [debug] [output:loki:loki.0] logs-prod-006.grafana.net:443, HTTP status=204
[2025/01/14 17:45:08] [debug] [upstream] KA connection #35 to logs-prod-006.grafana.net:443 is now available
[2025/01/14 17:45:08] [debug] [out flush] cb_destroy coro_id=2
[2025/01/14 17:45:08] [debug] [task] destroy task=0x6a7b960 (task_id=0)
[2025/01/14 17:45:09] [debug] [task] created task=0x6b55ad0 id=0 OK
[2025/01/14 17:45:09] [debug] [upstream] KA connection #36 to logs-prod-006.grafana.net:443 has been assigned (recycled)
[2025/01/14 17:45:09] [debug] [http_client] not using http_proxy for header
[2025/01/14 17:45:09] [debug] [output:loki:loki.0] logs-prod-006.grafana.net:443, HTTP status=204
[2025/01/14 17:45:09] [debug] [upstream] KA connection #36 to logs-prod-006.grafana.net:443 is now available
[2025/01/14 17:45:09] [debug] [out flush] cb_destroy coro_id=3
[2025/01/14 17:45:09] [debug] [task] destroy task=0x6b55ad0 (task_id=0)
[2025/01/14 17:45:10] [debug] [task] created task=0x6c2dd80 id=0 OK
[2025/01/14 17:45:10] [debug] [upstream] KA connection #35 to logs-prod-006.grafana.net:443 has been assigned (recycled)
[2025/01/14 17:45:10] [debug] [http_client] not using http_proxy for header
[2025/01/14 17:45:10] [debug] [output:loki:loki.0] logs-prod-006.grafana.net:443, HTTP status=204
[2025/01/14 17:45:10] [debug] [upstream] KA connection #35 to logs-prod-006.grafana.net:443 is now available
[2025/01/14 17:45:10] [debug] [out flush] cb_destroy coro_id=4
[2025/01/14 17:45:10] [debug] [task] destroy task=0x6c2dd80 (task_id=0)
[2025/01/14 17:45:11] [debug] [task] created task=0x6d05eb0 id=0 OK
[2025/01/14 17:45:11] [debug] [upstream] KA connection #36 to logs-prod-006.grafana.net:443 has been assigned (recycled)
[2025/01/14 17:45:11] [debug] [http_client] not using http_proxy for header
[2025/01/14 17:45:11] [debug] [output:loki:loki.0] logs-prod-006.grafana.net:443, HTTP status=204
[2025/01/14 17:45:11] [debug] [upstream] KA connection #36 to logs-prod-006.grafana.net:443 is now available
[2025/01/14 17:45:11] [debug] [out flush] cb_destroy coro_id=5
[2025/01/14 17:45:11] [debug] [task] destroy task=0x6d05eb0 (task_id=0)
[2025/01/14 17:45:12] [debug] [task] created task=0x6d1f960 id=0 OK
[2025/01/14 17:45:12] [debug] [upstream] KA connection #35 to logs-prod-006.grafana.net:443 has been assigned (recycled)
[2025/01/14 17:45:12] [debug] [http_client] not using http_proxy for header
[2025/01/14 17:45:12] [debug] [output:loki:loki.0] logs-prod-006.grafana.net:443, HTTP status=204
[2025/01/14 17:45:12] [debug] [upstream] KA connection #35 to logs-prod-006.grafana.net:443 is now available
[2025/01/14 17:45:12] [debug] [out flush] cb_destroy coro_id=6
[2025/01/14 17:45:12] [debug] [task] destroy task=0x6d1f960 (task_id=0)
[2025/01/14 17:45:13] [debug] [task] created task=0x6eb6400 id=0 OK
[2025/01/14 17:45:13] [debug] [upstream] KA connection #36 to logs-prod-006.grafana.net:443 has been assigned (recycled)
[2025/01/14 17:45:13] [debug] [http_client] not using http_proxy for header
[2025/01/14 17:45:13] [debug] [output:loki:loki.0] logs-prod-006.grafana.net:443, HTTP status=204
[2025/01/14 17:45:13] [debug] [upstream] KA connection #36 to logs-prod-006.grafana.net:443 is now available
[2025/01/14 17:45:13] [debug] [out flush] cb_destroy coro_id=7
[2025/01/14 17:45:13] [debug] [task] destroy task=0x6eb6400 (task_id=0)
[2025/01/14 17:45:14] [debug] [task] created task=0x6f907a0 id=0 OK
[2025/01/14 17:45:14] [debug] [upstream] KA connection #35 to logs-prod-006.grafana.net:443 has been assigned (recycled)
[2025/01/14 17:45:14] [debug] [http_client] not using http_proxy for header
[2025/01/14 17:45:14] [debug] [output:loki:loki.0] logs-prod-006.grafana.net:443, HTTP status=204
[2025/01/14 17:45:14] [debug] [upstream] KA connection #35 to logs-prod-006.grafana.net:443 is now available
[2025/01/14 17:45:14] [debug] [out flush] cb_destroy coro_id=8
[2025/01/14 17:45:14] [debug]  [...]

2025-01-14 17:49 UTC, 0x006EA1E5 commented
Screenshot of Grafana Loki, showing the remote logs with structured metadata fields `a` and `b`:
![image](https://github.com/user-attachments/assets/3cade140-0d3a-4d69-9461-cbc1d5f0bfeb)

2025-01-17 16:08 UTC, 0x006EA1E5 commented
I have now added a docker compose at `docker_compose/loki-grafana-structured_metadata_map`.

n.b., to run this for the branch, we of course need to build the image so that `fluent/fluent-bit:latest` contains the local changes. I did this via `docker build -t fluent/fluent-bit --target=production -f dockerfiles/Dockerfile .` as described in `dockerfiles/README.md`.

Running this, we can go to the Grafana instance running at http://localhost:3000/ and see the logs with the expected structured_metadata: 
![image](https://github.com/user-attachments/assets/7dbcbc0b-3922-4931-9ae4-5a3f8f080408)

I have an slightly different / updated fluentbit config for this:
```yaml
service:
  log_level: debug

pipeline:
  inputs:
    - name: dummy
      tag: logs
      dummy: |
        {
          "message": "simple log generated",
          "logger": "my.logger",
          "level": "INFO",
          "hostname": "localhost",
          "my_map_of_attributes_1": {
            "key_1": "hello, world!",
            "key_2": "goodbye, world!"
          },
          "my_map_of_maps_1": {
            "root_key": {
              "sub_key_1": "hello, world!",
              "sub_key_2": "goodbye, world!"
            }
          }
        }

  outputs:
    - name: loki
      match: logs
      host: loki
      remove_keys: hostname,my_map_of_attributes_1,my_map_of_maps_1
      label_keys: $level,$logger
      labels: service_name=test
      structured_metadata: $hostname
      structured_metadata_map_keys: $my_map_of_attributes_1,$my_map_of_maps_1['root_key']
      line_format: key_value
      drop_single_key: on
```

2025-01-23 11:02 UTC, patrick-stephens approved these changes
Looks good to me but @niedbalski what do you think?

2025-01-23 11:02 UTC, patrick-stephens commented on docker_compose/loki-grafana-structured_metadata_map/docker-compose.yml
> +      - ./config/fluent-bit_loki_out-structured_metadata_map.yaml:/etc/fluent-bit_loki_out-structured_metadata_map.yaml
If you mount this to the default location then you can also remove the `command` override - although that only is true currently if it is the legacy TOML format config.

e.g. this would mean no need to have a `command`:
```yaml
      - ./config/fluent-bit_loki_out-structured_metadata_map.conf:/fluent-bit/etc/fluent-bit.conf
```

2025-01-23 11:02 UTC, patrick-stephens commented on plugins/out_loki/loki.c
> +                         * Does this need optimising? For example, to handle
Simple is better I think unless it causes an impact. I'd be tempted to keep a naive initial implementation that is simpler and optimise later with specific test cases then.

2025-01-23 11:02 UTC, patrick-stephens commented on tests/runtime/out_loki.c
> +        flb_test_structured_metadata_map_single_missing_map},
Probably but we will know when we find them!

2025-01-23 11:04 UTC, patrick-stephens commented
FYI I'm seeing the K8S event test fail in other PRs so I think it is a flake: https://github.com/fluent/fluent-bit/actions/runs/12834843167/job/35870345004?pr=9530

2025-01-23 13:33 UTC, patrick-stephens commented
@0x006EA1E5 could you clean up the commits and/or squash them?

2025-01-23 14:52 UTC, 0x006EA1E5 commented on docker_compose/loki-grafana-structured_metadata_map/docker-compose.yml
> +    image: fluent/fluent-bit:latest
like this: 
```yaml
    build:
      context: ../../
      dockerfile: dockerfiles/Dockerfile
    pull_policy: build
```

2025-01-23 14:56 UTC, patrick-stephens commented on docker_compose/loki-grafana-structured_metadata_map/docker-compose.yml
> +    image: fluent/fluent-bit:latest
no need for pull_policy and I'd just leave it commented out once you've tested it - main thing is it allows people to see how to build vs pull

2025-01-23 14:56 UTC, 0x006EA1E5 commented on docker_compose/loki-grafana-structured_metadata_map/config/loki-config.yaml
> +#  reporting_enabled: false
Should I disable this?

2025-01-23 14:56 UTC, patrick-stephens commented on docker_compose/loki-grafana-structured_metadata_map/docker-compose.yml
> +      - ./config/fluent-bit_loki_out-structured_metadata_map.yaml:/etc/fluent-bit_loki_out-structured_metadata_map.yaml
No, this is fine and yeah we will be moving to YAML by default for 4.0.

2025-01-23 14:57 UTC, patrick-stephens commented on docker_compose/loki-grafana-structured_metadata_map/config/loki-config.yaml
> +#  reporting_enabled: false
Not unless required I'd say

2025-01-23 16:21 UTC, 0x006EA1E5 commented on docker_compose/loki-grafana-structured_metadata_map/docker-compose.yml
> +    image: fluent/fluent-bit:latest
This seems to be working locally now

2025-01-24 21:28 UTC, edsiper requested changes

2025-01-24 21:28 UTC, edsiper commented on plugins/out_loki/loki.c
> +            if (flb_ra_get_kv_pair(kv->ra_key, *map, &start_key, &out_key, &out_val)
flb_ra_* API do not use msgpack-c return codes like `MSGPACK_UNPACK_CONTINUE`, need to check the return values and adjust it

2025-01-27 15:39 UTC, 0x006EA1E5 commented on plugins/out_loki/loki.h
> +    struct mk_list structured_metadata_map_keys_list; /* list of flb_loki_kv nodes */
Do the comment start positions need to be aligned, or is it okay for this one to stick out further?

2025-01-27 18:11 UTC, 0x006EA1E5 commented on plugins/out_loki/loki.c
> +            if (flb_ra_get_kv_pair(kv->ra_key, *map, &start_key, &out_key, &out_val)
I'm a bit confused as to the meaning of the return code from `flb_ra_get_kv_pair`. [I see from the source ](https://github.com/fluent/fluent-bit/blob/master/src/flb_record_accessor.c#L761) it is commented that this should 

> Returns FLB_TRUE if the pattern matched a kv pair, otherwise it returns FLB_FALSE

Where `FLB_TRUE` is `1` and `FLB_FALSE` is `0`

However, actually reading the code, if this *doesn't* hit the `FLB_FALSE` code path, it actually just returns whatever the following call to `flb_ra_key_value_get` [returns](https://github.com/fluent/fluent-bit/blob/master/src/flb_record_accessor.c#L772), and function `flb_ra_key_value_get` actually seems to [return `0` for okay, and `-1` for not okay.](https://github.com/fluent/fluent-bit/blob/master/src/flb_ra_key.c#L262).

It looks like we are getting return codes as follows:

* Valid RA, normal happy path - this will delegate to `flb_ra_key_value_get` and return `0`
* Syntactically invalid RA key, such as `$$` - this will return `FLB_FALSE` (also `0`) via [`get_ra_parser`](https://github.com/fluent/fluent-bit/blob/master/src/flb_record_accessor.c#L740). 
    * This PR then proceeds assuming things are okay, then to check `out_val` and finally log `No valid map data found for key $` (test case `flb_test_structured_metadata_map_invalid_ra_key`)
* Syntactically valid RA key, such as `$missing_map` which doesn't reference anything - this will  delegate to `flb_ra_key_value_get` and return `-1` (test case `structured_metadata_map_single_missing_map`)

It seems like the main option here to to test for not equal to `-1`, and then check `out_val`.

Otherwise, we have to change how `flb_ra_get_kv_pair` works to agree with its comment, which I assume would break some important things elsewhere?

2025-01-29 10:57 UTC, patrick-stephens commented on plugins/out_loki/loki.h
> +    struct mk_list structured_metadata_map_keys_list; /* list of flb_loki_kv nodes */
I'd say line them up if you can

2025-01-31 13:37 UTC, patrick-stephens commented on plugins/out_loki/loki.h
> +    struct mk_list structured_metadata_map_keys_list; /* list of flb_loki_kv nodes */
seems reasonable to me

2025-02-04 16:39 UTC, 0x006EA1E5 commented on plugins/out_loki/loki.c
> +            if (flb_ra_get_kv_pair(kv->ra_key, *map, &start_key, &out_key, &out_val)
@edsiper Any thoughts on this? I believe checking `!= -1` is the best we can do here.

2025-02-25 10:46 UTC, leonardo-albertovich commented on plugins/out_loki/loki.c
> +            if (flb_ra_get_kv_pair(kv->ra_key, *map, &start_key, &out_key, &out_val)
Your interpretation of the code is correct, IMO, what we should do is patch [flb_ra_get_kv_pair](https://github.com/fluent/fluent-bit/blob/master/src/flb_record_accessor.c#L769) so it returns `-1` if `get_ra_parser` fails and then explicitly compare the result of that `flb_ra_get_kv_pair` call against zero to ensure that the intention behind the code is clear.

2025-02-25 10:49 UTC, patrick-stephens commented on plugins/out_loki/loki.c
> +            if (flb_ra_get_kv_pair(kv->ra_key, *map, &start_key, &out_key, &out_val)
I think in this case though @0x006EA1E5 should then just check for the zero case (or FLB_FALSE) to confirm it is not that. Patching the kv_pair seems like something in another PR?

2025-02-25 12:36 UTC, edsiper commented
@0x006EA1E5 would you please add a JSON example that shows the before the option is set and the after so we can review the behavior intended to be implemented ?

thank you

2025-02-25 12:51 UTC, 0x006EA1E5 commented
> @0x006EA1E5 would you please add a JSON example that shows the before the option is set and the after so we can review the behavior intended to be implemented ?
> 
> thank you

Hey @edsiper, what kind of JSON do you need? 

This only touches the Loki output, so I could include:

* A JSON log input
* The JSON output from querying Loki against the ingested log
    * Both before and after the option is set

Would this be okay? 
FYI, this can be tested via the included docker-compose in `/docker_compose/loki-grafana-structured_metadata_map/`

2025-02-25 13:17 UTC, 0x006EA1E5 commented
> > @0x006EA1E5 would you please add a JSON example that shows the before the option is set and the after so we can review the behavior intended to be implemented ?
> > thank you
> 
> Hey @edsiper, what kind of JSON do you need?
> 
> This only touches the Loki output, so I could include:
> 
> * A JSON log input
> * The JSON output from querying Loki against the ingested log
>   
>   * Both before and after the option is set
> 
> Would this be okay? FYI, this can be tested via the included docker-compose in `/docker_compose/loki-grafana-structured_metadata_map/`

The below is the results for running this with `/docker_compose/loki-grafana-structured_metadata_map/`, which has input

```json
        {
          "message": "simple log generated",
          "logger": "my.logger",
          "level": "INFO",
          "hostname": "localhost",
          "my_map_of_attributes_1": {
            "key_1": "hello, world!",
            "key_2": "goodbye, world!"
          },
          "my_map_of_maps_1": {
            "root_key": {
              "sub_key_1": "hello, world!",
              "sub_key_2": "goodbye, world!"
            }
          }
        }
``` 

This is the output with the option enabled. As you can see, the `stream` section contains the keys for the structured metadata:

```json
[
  {
    "stream": {
      "hostname": "localhost",
      "key_1": "hello, world!",
      "key_2": "goodbye, world!",
      "level": "INFO",
      "logger": "my.logger",
      "service_name": "test",
      "sub_key_1": "hello, world!",
      "sub_key_2": "goodbye, world!"
    },
    "values": [
      [
        "1740489069234881956",
        "simple log generated"
      ]
    ]
  }
]
```

And here is the output with the feature not enabled. This also removes `my_map_of_attributes_1` and `my_map_of_maps_1` from `remove_keys. As you can see, `key_1`, `key_2`,  `sub_key_1` and `sub_key_2` are no longer in the `stream` section:
```json
[
  {
    "stream": {
      "hostname": "localhost",
      "level": "INFO",
      "logger": "my.logger",
      "service_name": "test"
    },
    "values": [
      [
        "1740489174234932650",
        "message=\"simple log generated\" my_map_of_attributes_1=\"map[key_1:\"hello, world!\" key_2:\"goodbye, world!\"]\" my_map_of_maps_1=\"map[root_key:\"map[sub_key_1:\"hello, world!\" sub_key_2:\"goodbye, world!\"]\"]\""
      ]
    ]
  }
]
```

2025-02-25 17:09 UTC, 0x006EA1E5 commented on plugins/out_loki/loki.c
> +            if (flb_ra_get_kv_pair(kv->ra_key, *map, &start_key, &out_key, &out_val)
So, I updated this to check `== 0`, which I understand to be the desired "correct" behaviour of `flb_ra_get_kv_pair`.

When `flb_ra_get_kv_pair` is patched as per the above suggestions, this code will continue to work.

2025-02-28 11:35 UTC, patrick-stephens commented
Ignore the container failures - it is a permissions problem I think for forks, they build ok but fail to push.

2025-03-04 13:45 UTC, patrick-stephens commented
Build and pushed manually: ghcr.io/fluent/fluent-bit:pr-9530

```shell
docker buildx build -t ghcr.io/fluent/fluent-bit:pr-9530 --platform=linux/amd64 --target=production --push=true .
```

2025-03-04 13:55 UTC, 0x006EA1E5 commented
> Build and pushed manually: ghcr.io/fluent/fluent-bit:pr-9530
> 
> ```shell
> docker buildx build -t ghcr.io/fluent/fluent-bit:pr-9530 --platform=linux/amd64 --target=production --push=true .
> ```

This image is now available for us, and my testing confirms it is working as expected 👍

2025-03-13 17:38 UTC, merged