bin: config: Provide maxstdio option for increasing I/O limit on Windows
fluent/fluent-bit pull request #9707
Opened 2024-12-11 10:46 UTC by cosmo0920

With default limit of I/O on Windows is somewhat small for large amount of log volume environment.
I provide an option to set up this limit up to 2048.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2024-12-19 20:09 UTC, edsiper commented
@cosmo0920 we don't do ulimit stuff in Fluent Bit, why should we do it for Windows ? (maybe we just need to update the docs for windows users ?)

2024-12-20 01:06 UTC, nuclearpidgeon commented
Is this limit something that can actually be changed at a system configuration level on Windows?

This is the MS doco about the setter function: https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setmaxstdio?view=msvc-170 . It seems to be specifically something that's part of the [Microsoft C runtime library (CRT)](https://learn.microsoft.com/en-us/cpp/c-runtime-library/c-run-time-library-reference).

There's some info here saying that the limit can be further stretched if you use specific Win32 libraries directory rather than this C runtime library: https://stackoverflow.com/questions/870173/is-there-a-limit-on-number-of-open-files-in-windows/4276338#4276338

2024-12-20 01:35 UTC, cosmo0920 commented
> @cosmo0920 we don't do ulimit stuff in Fluent Bit, why should we do it for Windows ? (maybe we just need to update the docs for windows users ?)

In Windows, we need to set up the ulimit like limit via `_setmaxstdio`. There is no API/mechanism without this API from C runtime.

2024-12-29 02:36 UTC, edsiper commented
thanks folks for the context. @cosmo0920 I suggest to rename this option to `windows.maxstdio`

2024-12-29 12:49 UTC, cosmo0920 commented
Sure, I'll rename it from the previous one.

2024-12-30 14:39 UTC, cosmo0920 commented
I rebased off the current master and added `windows.` prefix on the newly introduced parameter.

2025-01-08 15:37 UTC, edsiper requested changes

2025-01-08 15:37 UTC, edsiper commented on include/fluent-bit/flb_config.h
> +    int maxstdio;
use a prefix as well for the internal variable: `win_maxstio`

2025-01-08 15:37 UTC, edsiper commented on src/fluent-bit.c
> +        { "maxstdio",        required_argument, NULL, 'M' },
prefix is missing

2025-01-08 15:37 UTC, edsiper commented on src/fluent-bit.c
> +                                        "max_stdio", 0, optarg, 0);
name has an underscore

2025-01-09 06:07 UTC, cosmo0920 commented on src/fluent-bit.c
> +                                        "max_stdio", 0, optarg, 0);
Fixed in https://github.com/fluent/fluent-bit/pull/9707/commits/beff608dc69d81aab78a03eae041b25438783efe

2025-01-09 06:07 UTC, cosmo0920 commented on src/fluent-bit.c
> +        { "maxstdio",        required_argument, NULL, 'M' },
Fixed in https://github.com/fluent/fluent-bit/pull/9707/commits/beff608dc69d81aab78a03eae041b25438783efe.

2025-01-09 06:07 UTC, cosmo0920 commented on include/fluent-bit/flb_config.h
> +    int maxstdio;
Fixed in https://github.com/fluent/fluent-bit/pull/9707/commits/beff608dc69d81aab78a03eae041b25438783efe.

2025-03-29 16:53 UTC, edsiper commented
will merge after rebasing to avoid conflict.

2025-04-29 21:21 UTC, cosmo0920 commented
I rebased off the current master.

2025-05-08 14:31 UTC, edsiper commented
@cosmo0920 for this one please make sure to submit documentation updates.

2025-05-08 14:31 UTC, merged