filter_kubernetes: add owner references information into record.
fluent/fluent-bit pull request #9719
Opened 2024-12-12 17:59 UTC by shuaich

This change add owner references information into record when `Owner_References` parameter is set `On`.

This PR implements the feature request in https://github.com/fluent/fluent-bit/issues/9631.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [ ] Example configuration file for the change
```
filters:
  - name:                kubernetes
          Match:                       kube_*
          ...
          Owner_References: On
```
- [ ] Debug log output from testing the change
```
"kubernetes"=>{"pod_name"=>"fluentbit-gke-2p6b5", "namespace_name"=>"kube-system", "pod_id"=>"c759a5f5-xxxx-xxxx-9117-8a1dc0b1f907", "labels"=>{"component"=>"fluentbit-gke", "controller-revision-hash"=>"77665fff9", "k8s-app"=>"fluentbit-gke", "kubernetes.io/cluster-service"=>"true", "pod-template-generation"=>"1"}, "ownerReferences"=>[{"apiVersion"=>"apps/v1", "kind"=>"DaemonSet", "name"=>"fluentbit-gke", "uid"=>"1a12c3e2-d6c4-4a8a-b877-dd3c857d1aea", "controller"=>true, "blockOwnerDeletion"=>true}], "host"=>"xxx-2a9c049c-qgw3", "pod_ip"=>"10.128.0.111", "container_name"=>"fluentbit", "docker_id"=>"2acc16e490e8d6xxxacbb45fe6c519c4f55593e00cd59ff3178b3a92965c88", "container_hash"=>"xxx", "container_image"=>"sha256:5163d704420bb702ba4df39cc774c2961b4f5450ab843aa85f0e92aeb2321ea2"}}
```

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

2024-12-20 16:16 UTC, JeffLuoo commented
LGTM

2025-01-08 17:53 UTC, shuaich commented
Gentle ping. May I have the feedback on this PR?

2025-01-09 22:08 UTC, edsiper requested changes

2025-01-09 22:08 UTC, edsiper commented on lib/cprofiles/src/cprof_profile.c
> -}
please do not touch this file

2025-01-09 22:18 UTC, shuaich commented on lib/cprofiles/src/cprof_profile.c
> -}
Good catch. I had to manually apply local changes to cprof files to make the build and run the unit test. I then manually reverted those changes but still got the one line diff, which I don't still understand.

Do maintainers have the permission to revert this file change?

2025-01-10 00:42 UTC, shuaich commented on lib/cprofiles/src/cprof_profile.c
> -}
It turns out there is an additional newline character appended by my vim editor. `:set noeol` fixes the one diff. See https://stackoverflow.com/questions/1050640/how-to-stop-vim-from-adding-a-newline-at-end-of-file

2025-01-16 22:14 UTC, shuaich commented
@edsiper Could we backport this PR to v3.2+?

2025-01-17 23:06 UTC, shuaich commented
https://github.com/fluent/fluent-bit/pull/9849 to merge to branch 3.2.

2025-02-28 15:43 UTC, merged

2025-03-01 01:23 UTC, shuaich commented
Documentation PR: https://github.com/fluent/fluent-bit-docs/pull/1577